import type { IActivity } from "@/types/services/activities";

export default (): IActivity[] => {
  return [
    {
      stravaId: 9247123624,
      name: "Rower #15 2023",
      distance: 66525.7,
      movingTime: 9432,
      elapsedTime: 9779,
      totalElevationGain: 436,
      sportType: "Ride",
      startDate: "2023-06-11T14:32:18",
      startDateLocal: "2023-06-11T16:32:18",
      startLatlng: [50.21873474121094, 22.110294342041016],
      endLatlng: [50.21695327758789, 22.109073638916016],
      private: false,
      averageSpeed: 7.053,
      maxSpeed: 17,
      averageCadence: 72,
      averageWatts: 97.2,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 917,
      calories: 1565,
      deviceName: "iGPSPORT BSC100S",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "ajoqHil}eCWAIDILCROhAGFGA_d@uYK[Fw@?wAKsGCSGMKEK?UCEMMiD[_FCkBIo@YyAQg@UYoCgB_@g@@QLk@`AeC~HcMrBoC|IcKz@gAfG}G~FmFlMyMbCqCtWeX`@a@p@aBF{@FiB`Bmg@RmBt@_DAMIUyAwBgIkM}PwWCQ?QjGcTjEyOhFuRxBmIlEwRzAuF|BkHxDuNd@yAfBaEt@kBfFoPv@uCXkBJqBBwBM{BK}@_AgGQoBIqJJqA`B}F|CoH\\m@pBsA`@g@t@yAvAaETi@PWl@q@dDsC~@cAnJmMx@eAj@i@bAs@lEwChAm@`AQlEg@lAKxAc@zDmCzEoD~@mAdBoDp@}Af@}@|@qBx@eC^mBZqB~C}Th@eEzCgk@AkHDwAJqAdBaLbAuH\\cBh@qAjBkDr@{A^qBViB|C{UFYFIFEH?JBrBt@nDlAbCd@fGdAd@Bf@E|@U|@[RK~@_Ar@iAt@aBb@_Br@{CdCwGt@eBpAkCbDgJh@mA|@qAt@y@l@_@tCqA`A_@jCk@~E_ApAG~CZfAXp@`@z@~@lBpCjA`AbBt@~@t@dA`@P@t@IzCk@fMoCvA]t@WxAcAvUsRjA}@t@_@zDsAxBs@J@HFDLf@jIBVB@@Kg@yJHMjEyAhAe@vCaBjAm@nE_ApAa@bBu@z@a@xA{@rG}DhP}IfAWdAAtEBhAUJIJMh@cA|R_k@bAaCj@q@`Ae@ZMzKgDjAUjACfA@jAx@|A~Ax@fAHPZpANrBJxB@h@rAv@PXZtAHJJDJ@vCJpIPhHJfAFbAh@bAlAP`@\\pAHBH?jAa@b@EVDJHd@v@p@rA\\pAJN|AnA`Al@hE~DbAj@vB`ArBn@l@VjHhDH@HAhAo@P[Nm@RQhAe@~@o@hAc@jAStC}@tBg@jA_@tC[z@[f@WdASfAL^XHLDP`@lCt@hBd@z@pAlAdBfAvCxBdAp@hA`@T\\`@lAb@jB~@hBFj@Cl@SvASrBApBHtCVbCLf@h@~AdBvDl@dBf@hBPbAPvBF|APvHBLBD`@@|@GbAOrF{@nQ}CdBc@VWtAoEv@kAzBgC|@k@lAGlA?tAHLCZkl@D}Db@aFl@cNAoA[mF?QDkBfA}P?qBQuP_@wBuCsK[}BIkBWuKIuCi@eKEgFFqBToBdBmILqBRwJ^yINqBnAmML_CKqCUqB_@iBi@}AiBmEg@cB[kBSoB?Q@iIDOHIJCbF_@tCWhA]~B{ARWTQfBgA~FaE^QhAK|EAbAXjAp@vE`DbGnEfAbAHLh@zAV|@b@lA|@fAfCxBdAn@fA`@vA^xE`BbAj@LJl@zARpBJ|Az@vEh@dBp@zAv@rAXVtEpBjC`AbAVZCrAYNBhFvAfAd@~EtCx@Zx@BtEInAF|AdAhAn@|@n@lAf@J@jAQnBc@R?DFD\\XD?BN@\\MDGLIVm@PIrAGvBEfBS|JmBxBm@jAPnAz@VLdA\\lBh@VIZ[rAoCf@g@nC_B|@q@xBkAf@[l@k@jAyAr@u@\\c@lCwEd@gAd@iBz@yDj@cBFIHGj@S`Ck@jA]|@]xA_AhFcEzAaAjDeBvFgCzCcA`CeAjAYZ@lAPhAXnDlBdA\\hABhBQhDBr@GjASrA_@~AMd@MhAq@n@g@hAg@jAQrAI~CBjBFBE@SJZNJ@BAJ}FlG{@jAe@`Aw@bCiBhGoElO{@`DKv@C|@B|@F\\JXrAzB^t@L\\Hb@Dd@?d@OlBIdBE~BEvBArBBnBLdCx@~EDr@Er@_@zAgAdCe@pAsKrZe@rBSbA{Fj]Cp@AtBCh@Gp@_@bBe@|@{@fAk@zAc@lB[lB_DtTYtAqBbH[pAiFvU]hB{@vFOvBi@b@e@zBE^O`@sA`C]d@g@f@]b@EJkAxLaAnLC^o@nG@ND\\l@fBd@lCN|@ANALGHGBaA\\{BhAe@L[CGDELSr@CTG`AI~CIlBBx@DZJVnAlCb@fA?TCPIN{BlD_B~C]j@aCzCSf@ET?X\\lCF`AARO`@m@fAWh@y@rC]rACxBBlB?nBAdf@CvEAnJVvI@pBMtBi@lF_CxSEl@UhIs@xMWvJ}AjU[lIERKNMFyAb@eAj@yBjB]PoAVO?kA[gGiCiAy@eAaAc@[uAq@{@i@a@S{@GeAp@cA|@qAr@{JlCmAXmDpA}LxDmAb@aHfDeFfCiA~@gAhAiAj@sFxAkDbAsAPqAF{A_@oPyF{@Sc]aEgA@gA\\WLaAr@mCbB[PSBWVuA`@e@FkABc@AkJi@eA?SBaAVEECIC_@CCE?EPAn@CJeAnAq@vA_DrIw@bAoAl@mCjA}E|BiAh@mAv@}@dAw@tAqDxH{@rAk@j@iAl@}@VuRpCgARoAn@gAlAqJzMuLfQq@xAGN[nBs@lLuAbW[bEe@zB}EhQYfBAf@BxBXbLArBWlBmA~EsOfl@o@tAw@lA{^ze@iBzBeAp@KBqJvBqCp@gGnA}@NeABo@CgI}@uDc@aBQ[AgARkg@~PwDjAw@\\{JhD_ADw@YuBaCwDsEE[EsBEUEcAEkDLiD?a@y@wX_AyVEiCCgHAwSFoFTkFZiKLoF@_BCMMUGGKEcAWqFOq@USa@K{@IeJEgACGGCMDwEpCw@\\eDp@_G`AqAJwDPiAJqC\\gFt@qANeF^o@HyBb@yEf@yO|BwCPoTj@a@FKHGLId@SbHc@fMQnHaA`SEbCG|NAfPCh@IFI?eC_AiNwEuAu@wN}QaAy@kMwHy@a@iC_AiC{@eL_EgA]sAOkJIkA@gALyC|@g@Jq@HoGTmAH}@b@iAt@a\\fSgAh@sACwCaAYCKN_CdOCT?jBHh@Vt@v@bBfG~Kh@rBL~BLnCDxACLIHK@eFB}@AgAIkEiA_HuBiAOg@?_HRqAE_Dg@{A[a@MkC_AgAMKBwAbAwB|@cAh@iAx@iAp@a@Pq@PGDaAxA_XnXsBhBiFrFwCrC{@~@u@l@SHQNcA|AuD|DwQrS}@hAeD~E}DlGq@hAc@lAYz@Kj@@NDH`DzBRRN\\b@fBHx@DtBXpDPbEDRD@\\?FBDFDVPpIGnABX~@l@\\j@fInFl@d@lG`EnIlFdAl@t@ZJAHKVgAHOLEL@jAx@fAp@jAl@jBl@HP",
      summaryPolyline:
        "eqpqH_c~eCWe@CcLKa@s@Ww@ePu@qC{DyCpAcExJmOrMqOnz@}{@rAcCpBsl@fA{Gi^qj@Cc@`Usx@bL{d@vHaXbEgK~GeUXkBNiFkBqP@cM`B}F|CoHpDiDbDeIdHaHhLsOfKcHvLiBxIiG|BaC|F}LxAsFdFu^zCgk@AkHPiDfE{XhEyIdF{]`I`CjKjBlAAnC}@~@_AhBkDvA{FzM_]rBkCdGqCjJkBpFRxBz@tFrGzFnCfX{F|ZuVjG_CtB]t@rJe@eKHMtG_CbFoCdKwCr]yRxLu@t@qA`Uao@hCeBfN}DrCAbF`Fd@bB\\vGrAv@v@zBrZx@fCvBn@rBfDS`ClFhJ|HhS~I|Ao@t@{ArEyB|SiFlCEh@f@f@~CzAdDnInGnCrAzC`IBxAg@jEFfGd@jD|D|Jx@lDn@zOfDOh\\}FlBgFrDsE|@k@~FA`@ir@pAeU]oIlAiTQgTuDkO[}B{Aeg@\\aFdBmI`AcYlB_UKqCu@{EsCkHcAoESaC@iINYnMyApPaLfHMbAXnRfNnBtFdE`EpOjGl@zA^nEz@vEzA`EpAjBdLjE~BYhFvA`JvE~I@rHlEfEs@R?t@p@zAwArHa@vN{CxFxBdC^vCsEnJyFjE_FrD_HtCqK`IcC~KeI`UwJjAYhBRxFfCnC`@fIU~FaAhFoCjAQ~I@DY\\j@_GxGaBlCmL|`@OtBJzA~BjE\\fB_@xJCzIfAdJ?fBaPfd@uHbc@QbG_@bBmC`F_Fp[qKbd@iBxMi@b@{@|D}D~FaExc@hBpJoEbCaAHe@|AWhKdC~GgGzKuCbE\\rGuArCwAfFGdcAXhM}Dj`@aBzc@yBx_@Qb@mDvAwC|B_BVsIeDsDwCsDoB{@G{EbDcc@vMgOnH{EtDsNnDmDWkRmGc]aEoC^oHrE{Bh@{Mg@{CZWs@KlAwBfD_DrIw@bAsQxIuBzCqDxHgB~BgCdAuRpCwCbAyLhPuLfQy@hB[nBeDtj@}GlXZdQY`FaRfs@gBbD{^ze@oDlDuYlGqVuBqz@fYmCd@sB{AwFoHWkILyF_C{t@Aaa@dAs`@Yk@oA]cHe@_@}ASuLeHpDeLrBe_@lD}[rEsY~@a@NQr@iAz_@aA`SWxe@uUkIwN}QmOqJsV}I{Cm@wLG{H`B}I^qb@jWeGiAkCtOC`CxAbEfG~Kh@rB\\vJaKBkN_EcNAqN_DoOdIaZh[mSxRo[x^uKvPgAdEzDxCr@dCz@dP|@x@HhLZ`@",
    },
    {
      stravaId: 9226831430,
      name: "Rower #14 2023",
      distance: 44747.3,
      movingTime: 6218,
      elapsedTime: 6218,
      totalElevationGain: 230,
      sportType: "Ride",
      startDate: "2023-06-08T13:08:00",
      startDateLocal: "2023-06-08T15:08:00",
      startLatlng: [50.21852111816406, 22.110071182250977],
      endLatlng: [50.21693801879883, 22.109020233154297],
      private: false,
      averageSpeed: 7.196,
      maxSpeed: 10.57,
      averageCadence: 71.6,
      averageWatts: 97.8,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 608.1,
      calories: 1017,
      deviceName: "iGPSPORT BSC100S",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "whoqH}j}eCKG_@GWVY~@GDI?o[kSmAo@k@UGFCLArAFrBJzBr@`L?|@u@dCS\\KBMEwAoAm@}@S_@w@gBiAiD{@yCc@iAICIBGHs@vAq@dAeAjAqBdC{@`BqAdDQRI@IEGIc@eCGCC?CD[hCeC~HgAxDuEjQeAxD_A|Cc@pAm@xAKLe@NILEPE`A_@pAq@jBeE|Jy@bCa@`BM~@MvAK~DGnDKbOEbCEjK@vHMpIMrB}A`Ua@~Ee@vCgFhT{A~FqAlEgFjPsK|Y_InR{@~BkC|HyFvNkFdOg@`BkAlFwBtKcCtMg@xBwGbTcFhSi@|AgBfD_Tl^qBjD_FfJgC|Dm@xAkCvKIFKAaAaBO[Kc@[{C_@yBSSKC}AW{Gy@cF_AaC_@uEc@eAYc@QgAq@uCgC}Ay@iAWmGaAcAUqB_AoCuAcAKeFNwNVaMNmVYu@BKD}@x@}@t@mB`Aw@NkLAaFXgAGcAC]Pq@`Bi@lBWb@IFkA`@iAVmAKqLcF{@QKPIVMbBYnFGrBCrB?ji@Lj\\ElZBLDFrB`AfAT~B^VF@C_@EiDg@_CcAI?GJCb@@pGIjBGPSXmAl@qAZsH`BeJ~AcEx@}HnB{A`@KLGRBf@^xEtB`^b@bGfAjLlAlNP~BBh@AHCDE@GAiAy@uF{AkAIcDByDXkAS}CqAgAi@_Aw@s@qAWiBYqAc@i@IEWEkAJkDj@qANeADqAAs@C_A[S]EOYgB}@sE_@}@{@mA}DwEuE}EeC}BWKW?eCd@mAOmAe@oAa@}Cg@mAYkA_@wAo@i@q@m@aBe@gBi@gEa@qBGQkDkGy@sA_BqBkGiHq@aBi@}A_BeCe@sBuHseB]mJ}Cms@CwAFS`@MZGhAKdIiBhBYfB_@r@Q@ECGC?QP{Ch@wJtB{Bl@IAc@BCEEOCg@c@kJqBce@{@cRUgGEc@Q[UQmA_@yCw@gVeGsHiBmFuAMKIQGSCUYqG{@}NuBiX{Dof@c@iBGQaHiMe@mBM}B{@sQEuBD_S[aS?aCDQFOlIoIrAsAJGLCL@LFHLHNFh@VbEPfBHLJDJ?`D}@nJyCrNoExDqA~C}@`UcHdAYbDcAl@GFHDN|@fI\\zB~AvMfFb`@DjBHfARd@PJNB^IhCeAtFoBjVyIbEcBnDoA~EqBj@YtHeDdRcHfAe@j@Yr@{@n@eAj@iAl@gBjCuLRiBNaERmJBMFIFAJ@fAP`IbApAXlBh@~AVjAf@RZt@|Av@xAdBfCt@rAp@~Ab@nBRtBVn@HHJDJAHIhAyArCeD@GUsEQiBDyBrAwEZeBJs@nBy]BmACwAKsBAuA@}AFiBFk@FEH?fFj@dB\\nA^pDlAfGdBz@ZfEfBxC|Ab@PPBPCLKJUPo@j@yAhAoAhBkBpAi@hB?tAE^KpCwAhA]x@SL@ZP|@|@xB~Bz@dAx@hAr@rAbBlEr@lA`AvATTJ@JEHMFQxBgNXkBh@iEd@uBP_@~@iAbAeAz@qAbCkFn@iAh@s@bAaAdAaAdA{@p@a@f@MrACt@BXGHKLc@d@oFXmBFIJCL?fAZ`@Rb@HJEHMJ_@VoBnAoKh@gFHc@FOJIJCvBJhAC`Ao@FOh@kBt@kE`@cBJKLCL@~Ap@hA\\L@hAALE|C}A|@YjAGhAFhAThC`@jA?l@WdAcAz@iAv@oAl@wAh@eBr@aBTUdAWh@EpA[|H}DhCuArAaAtCUh@[n@_Bn@{BnEyMf@aBx@oDr@eB`Ao@n@IzAb@jPlK|CbCnARx@AHFFLj@nF`@nCX|Ad@tBf@nBr@zBl@`Bn@xAnAdCbC~Dfb@xo@jA|AHDH?FGLWt@oC|ByHd@gBdFcPPQ^EHENYZiAHGHA|EfChJtEhA^fCp@lAVhAl@vIrH|@nAXp@~BdHd@hCJtBJXb@nBJVH@HCNQ|AsDz@{Al@{@rBeC~@sAx@_BHCH@FJvBlHh@|Ar@|Ax@rAp@t@|@v@H?JENYf@aBReAq@gLWcG@mB@GBEB?tEvCdAt@fVtOJ?BETkAJ]HKJAJBpA|@fAn@dAh@fAX^NJLDT",
      summaryPolyline:
        "}wpqHgq}eCy@aC[HeB|CwDpE{@`BqAdDQR[Mc@eCO@[hCmExN{Ib\\qAjD{@j@KrA_@pAwFhNy@bCa@`B[vCSnJQfSCbUMpIyBz[[`Do@fD}Ib^eFlPkCpHoHdS_InRgE|LyFvNkFdOg@`BkAlFcHd^eGrRuFxTi@|AeDfGsUx`@_FfJgC|Dm@xAkCvKUDqA}BgAyHSSkVuD{G}@kBcAuCgC}Ay@{KoBaGuCcAK_d@v@cXUgCtBmB`Aw@NkLAaFXkCK]Pq@`Bi@lBWb@_D`AmAKqLcF{@QUh@MbBYnFKfF?ji@Lj\\ElZHTrB`A~E|@gEq@iCcAKn@@pGIjB[j@mAl@qAZ}YzF}HnBgBn@GRBf@^xEtB`^jE|g@Bh@ENM?iAy@uF{AkAIcDByDXkASeF{B_Aw@s@qAq@{Dm@o@WEiIfAeADeCE_A[Ym@wA{H_@}@yFeH{I{Io@KeCd@mAO}CgAkFaAcDoAi@q@sAiEi@gEi@cCeF_JkJ{K{A_E_BeCe@sBuNghDFS`@MdBSvOcDt@WGGQPoSlEq@Cm@cLcEo`AEc@Q[}FiBig@eMW]Ki@YqG{@}NqHy_Ak@{BaHiMe@mBiAqUEuBD_S[cWVk@bLaLZA`@d@p@tIHLVD``A{YhF}Al@GLX|@fIdJvr@NrDRd@`@N~n@mU`QqHxUcJbBaCj@iAl@gBjCuLRiBb@oPJW|KtA~GzAjAf@`CrEzCzEp@~Ab@nBRtBVn@TNTK~EgGg@}HDyBrAwEf@yCnBy]BmAQaHHgEFk@FEpFj@tD|@tNnEvKzE^OhA_DrD{DpAi@~DEpDcBpCo@xAnAtDdElB|CbBlEr@lAvAlBVCP_@xBgNbAuHd@uBP_@bCoCz@qArDuHlBuB|D_Df@MhC?b@SLc@d@oFXmBFIXClCx@TSb@oCxBwRPs@VM`EF`Ao@p@{Bt@kE`@cBJKZAvDpAvAG|C}A|@YtC?rEv@jA?l@WdAcArByCl@wAh@eBr@aBTU`Ey@|H}D|EwCtCUh@[n@_B~FuQf@aBx@oDr@eB`Ao@n@IzAb@jPlK|CbCrCXtAlK~@rEzAjF|AzDnAdCbC~Dfb@xo@jA|ARDT_@xEqPdFcPPQh@Kj@cBRIfQ|I~GhBhAl@vIrH|@nAXp@~BdHd@hCJtBz@`DRANQ|AsDz@{A`DaE~@sAx@_BRALX",
    },
    {
      stravaId: 9202990318,
      name: "Rower #13 2023",
      distance: 52278.5,
      movingTime: 7773,
      elapsedTime: 8341,
      totalElevationGain: 214,
      sportType: "Ride",
      startDate: "2023-06-04T14:59:58",
      startDateLocal: "2023-06-04T16:59:58",
      startLatlng: [50.21694564819336, 22.109172821044922],
      endLatlng: [50.216941833496094, 22.108997344970703],
      private: false,
      averageSpeed: 6.726,
      maxSpeed: 10.57,
      averageCadence: 67.8,
      averageWatts: 87.8,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 682.4,
      calories: 1250,
      deviceName: "iGPSPORT BSC100S",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "{~nqHie}eC?PBB@AS]QKmBm@SKiBmAcAo@MEMBKHa@pAGFG?wZwRoAs@}@_@IHCNA`BVbGVxE\\xEKd@g@~AQb@KHMAKGaA{@{@kAk@eA_AiCyBkHM]IEI?IF_AdB_FjGs@rAkBfEIBIAGGc@sBEGGAEDEH]zBgDvKuGvVkBnG]bAo@zAKJYFKFGLEPC~@Wz@wA|DwCbHu@lBWv@i@jCGh@MfBS~LGtKG`CEzI?`MEhDInBMrBoA`RY~DQnBe@nCaHhYiAfEk@jBmEdNk@bBaKnXaIpRm@bBsCpIyErLeGtPq@xBaCdL}ElW}@xCoEpNi@hByDvOm@pBm@pAoBpDuU`a@gFpJqClEo@zAe@dBoBjI[rBUrCuEzt@IpBAbCHlB\\hGTtDPpBf@tC~ExS\\tBBn@FrFJrBRvAf@dFFvBPpP?zBAV]jB_DfKKDYQUq@UWSM[AyAQYDaDDoD`@aCd@sCb@_Cb@a@Js@XiBd@_B^}A`@s@Lg@HmAB_BJkBTYJCPBpFIvRBd@GvD@nBMvAA|ABJ@pAGHmAZaFhAqCj@gALsABeKAgc@DcAK_DeAuAGyCJcER}CRgABkDV]?eAAaBSaAWmAUoAQ[DcAXsALsHWcDWiD[qAWkAo@cEqD_@e@k@yBmAuFm@gBaAiA{C_Dy@gAo@uAo@qAIGKCeAHyB\\k@DmCqAwEoAqAMaB@AB^@@A?EI?iA?yCVqABu@WCBEN?Vf@`G~@lM?\\AByCv@g@DQJOAOSOe@oAoDEGc@]o@?UBCL?^GpBWnBM`@{@tAyAnEk@nAYPaDf@oANmAb@aIrEqGdEwFhDs@f@KLQ`@}AbIaCvMuFz[oBtL[~B_D~PaD`Mw@dCyKt[m@~Au@hBCPg@nJOlBW|BiAjHQvAOLIEsAwAkB{BgCgCeCoBqEiDmCoBmS}LaFqCeAs@iAq@gAiA}DgJ_IsRuBuEEEM?[T}FtB_A`@M@AF`EaB`Cy@h@WF@DDjC`G|DpJt@~AjFjMVb@x@t@NJiA_AcA{B{HiR{Tii@q@gBkFoMaHoPw@cBaEaKkEgK_B_EmEkKs@mBg@iAOs@F]DEv@]dNoDvTsGhDgALO@KE{AiCcd@kAkTsDen@yAiWaCic@eAaQcAqQKuB?e@OoAIcAFPRjBHDhAKfDc@vKyAhFm@nALhAKjK_BhImAlAOR@DDFTFpC[nBQb@W^?FLMf@iAT_BIoCDUJIbB_@jBYdV_DnMiBJ@NG@?FHFNpGjzAd@~Jh@pBdA|Ar@`Bf@xAx@jAtB~B~DzEz@nAbD~Fl@|A|@|Gb@bBl@|AHPLLx@h@jAb@xCr@jANhAVhA^rAf@rA?fAWx@IZP`CzBjDnDfE`F`AnAt@nBz@hEf@vBDH`Ah@pCDrAAhHgAt@JJHTZFP^nCr@`BbA`AhAl@xClAjAXnDUzBGnA?rAR`EfAtBhADE@G@c@]_EYsCq@eIy@oIYsD[qE_ByXq@aJ@OBKHGHE`LkCxOuClJsBlAg@p@w@Fc@BgFCgHDw]IoVBsj@BwBJwBZaGHs@HKJAJBnKrEzAj@lACjBe@LGZYJOv@qCXw@JOLILEn@?lAH|EWbKB`AAjA]fAi@vAmAd@i@RIfC@zEFfAA~KN~NUrIQrHSp@Fl@X`CpAxAj@jAXfG`At@PhAf@|@r@fCxBt@b@fA`@lAPnCVnANbGhAvFt@dCXp@NLLHTDTr@|FDN`@v@r@jAHFJAJQj@oBR{@B_@hAkEXq@l@kAfCaEtDeH|AqCzT}_@lBuDn@iB~EwRrGwSt@mD`DiQfCyLd@cBtFwOvFqNpDqK|@{BdG_OvJyWpAoDnF_QzBmI~EsSb@qBRoA^yD`@mFjAwQHqBD{BByIDeBFOJEJBJHpEzFdBtBlBtBhA~@~HtEbEzBjA\\HAFEJU^gDP_CHqBRmLJuJVcMHeKMyOHsF@yBWsN_@qLQaHKqI@_CPcDLgDPUr@wAn@_Bf@}@v@mAzBoC`AwAr@wAFIHEH@HJhA`Ef@|Al@hBr@~AlAjB|@|@\\TH@HCHIr@yBJ_@Be@c@oG_@oIEyB@{@DIJ@`BdAzKlH`OjJHKXkAJ[HGJAdEfChAd@bATHPBT",
      summaryPolyline:
        "}xpqHgt}eCWc@]Pu@zA_FjG_DzG[Ec@sBMIKN]zBgDvKuGvVkBnGmA~Cq@ZGLIpAERiBdFmEpKaAbEUpCS~LOvOE|WEhDWbFiB`XYtC]hByFvUqBxHeHtTaKnXaIpRaEtLyErLwHnTaCdL}ElWmGjSqGrV}CbGuU`a@gFpJqClEo@zAuCpL[rBUrCuEzt@IpBAbCf@vJf@fHf@tC~ExS\\tBJbHJrBz@|HXhTArC]jB_DfKKDYQUq@i@e@uBS{DJoD`@uKlBqLzCuEXeC`@E`\\EfHMvAA|AD|AwHnByEx@ar@FcAK_DeAuAGmWnAgDU_F_AsDl@sHWmIs@qAWkAo@cEqD_@e@yBoJm@gBwGqH_BgDIGqADeDb@mCqAwEoAqAMcBD^@@GsA?kFZy@SEf@fBnUA`@yCv@iANOSeB}Ec@]eABCLGpCWnBM`@{@tAyAnEk@nAYPqFv@mAb@aIrEiOnJs@f@]n@_FzWuFz[oBtL[~B_D~PaD`Mw@dCyKt[cBhE{@nNW|B{AbKOL}A}AkB{BgCgCwIyGmCoBoZoQoCeBgAiA}N{]uBuESE[TkIxCAFlJsDLFjC`G~M|[Vb@hA~@iA}@cA{BkhAumC{AwDOs@Lc@v@]dNoDvTsGhDgAN[E{AuEoy@uM{|BoAmVYsCZ|BHDrZwDnALhAKvX{DLZFpC[nBi@bA?Ft@wAT_BIoCDUJInEy@re@oGNXvHjfBh@pBdA|AzAzDnJfLz@nAbD~Fl@|A|@|Gb@bBv@nBfAv@jAb@nHzA|CfArA?`Ca@ZPlHjHhGpHt@nBbB`IfAr@dFBhHgAt@Jh@v@^nCr@`BbA`AhAl@xClAjAXjH]nA?rAR`EfAtBhAFM@c@}D}c@{Bk_@o@qJBKRM`LkCxOuClJsBlAg@p@w@Fc@BgF@_g@IoVBsj@BwBTuEPcDHs@HKV@zMxF|A@jBe@h@a@|AyEf@_@|BH|EWdM@jA]fAi@pCaCjYVfc@{@p@FnDjBxAj@hKlBhAf@dElD|BdAlHx@bGhAnL~ALLNj@x@lGtAbCTDv@aCV{AhAkEXq@tDmGrGwLzT}_@lBuDn@iB~EwRrGwSt@mD`DiQfCyLd@cBtFwOvFqNpDqKbI{RvJyWpAoDnF_QzBmI~EsSv@aE`AgLjAwQNmFH_MRUVLvHpJlBtBhA~@bOpIjA\\PGJU^gDZqFv@gf@HeKMyOJmJWsNq@sUKqI@_C^kI|CkGtFuHr@wAPORLd@`B",
    },
    {
      stravaId: 9157797524,
      name: "Rower #12 2023",
      distance: 53123.8,
      movingTime: 7619,
      elapsedTime: 7863,
      totalElevationGain: 301,
      sportType: "Ride",
      startDate: "2023-05-28T13:31:46",
      startDateLocal: "2023-05-28T15:31:46",
      startLatlng: [50.21697998046875, 22.109115600585938],
      endLatlng: [50.217044830322266, 22.10918617248535],
      private: false,
      averageSpeed: 6.973,
      maxSpeed: 10.664,
      averageCadence: 0,
      averageWatts: 93.8,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 714.4,
      calories: 796.6,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "c_oqH}d}eC@DCOOEGKEAG@k@Y]Ky@]gD{BKAKBIJO`@Mp@CHG@iBoAoN_JcBkAaB_A_DuB{@c@KCI@GLCPBlCz@fNN`B@t@ARaA|CIJM@s@e@c@c@aAuAeA_CmAuDkAkEGMIIKAKBu@~A[l@mBxBaBzBaAlB_AfCQXIHK?IEEMKs@Sw@GGGAGFOtAYvAm@pBg@tAqBzGqEfQsAxEkArDa@`A[f@IDY?KCKKcCuD}EwHsM_SaPwVGK]WMCK@IJUlA[z@iD`MgAnDcBxEuCxI_BlE{@tCMXe@d@i@XiAz@mBt@mAl@eBbAe@h@gAvBUZo@f@k@\\oAdAqDzDe@v@k@jAw@hBw@hGIb@s@xBkA|C_AlC]x@w@bAqArAi@d@aAfA]ZwChDo@p@aCnCk@j@m@h@uC|By@|@mAz@q@n@u@`@kC~@[T_AbAk@|@S^[nBWjCW`A}@nBgD`GeAbBw@vAo@`AKLg@`@sA|@q@l@k@~@}AbDm@`AYZWXcAx@YPi@TIFINEPClD_@nSMlDOjH_@lJe@pJw@pQS`HMzBKhF@lACvEFzD^lIRpCDvAF|@l@`TJrAXlBb@lCfB~IPjANpAr@xE\\pCvDz^^rCd@nCx@lET`Ah@lB~JxYl@zAtArCBLANo@|AsBdI]zAGHK?IGaAgBO[Ia@OgBWyBQo@QS_@KyJmA{Ci@G?_@KqAUoBWu@C}@KaAMc@Mg@Qy@e@oAcAeB_By@e@e@OaAU_Dc@qB]m@MeAc@sDqBq@QmBBaHPyDDmCHaMPsWWq@@YHKFi@l@w@r@uBdAg@LcABqKAq@@{BTY@yBO]B[ROXy@`DM\\OV]Vk@RmAV_@D]CQG{Ao@iAk@mIkDGIAKBy@l@qJ|@yPlDgl@x@gOLkCGWi@J}B`AeBj@{@^gB|AiDdDmArAOHQAMOu@qB[eAAHBHfArCZl@@JGPi@x@_EzEo@b@}@b@g@Ns@?cAWIAS@QJu@x@yAnAk@p@aAlB_@j@oBjC_AvA}@fBcAzA_@n@sAlBa@b@WRcA^g@D[?i@OcAKYGkBMe@Hg@N{@x@i@x@Wr@St@gA~CoB~Di@x@oArAiBvAe@VsBr@c@R]\\WPSTs@b@y@\\e@Fo@RgAPyAN_CZW@}@PY?gARkAHmDn@qBTyDl@c@Da@F}CZaCZkFx@kD`@sB\\uDd@yATsDd@g@HmAL{@PoBTuATw@Be@FIGEi@a@aMwAg[MkDc@{Ia@sKs@yOaBi`@GgAw@uREe@M]IKWK{Cq@kEkAuD{@_J}BkB[mDeAw@OsGcBYOKMKg@QaGy@wNSsBIoAcBuRMmBGa@GMWQmF}B{@e@a@c@Q]s@uBSWWOcBi@{@U}@IsEQ{@Ic@U]a@Q[]_AQYIIUKwCUa@IOGQK[c@oAmCg@o@yNiMoGoFwEaDkFgDy@g@e@QmAO[AYBYNWV]d@}@xAMLE@EM@KFm@PUL[~@wD^oABSCIw@eA_@]cBmBWq@GeAGa@GOOWw@w@GAEDK\\UdB[dAwB`Ec@bAgDxGSXKFM?KG}@kAWSc@So@QiASa@EWBWFi@b@STOZSj@YhAC^D`@Lp@xAxFLz@JLFBb@FbE\\hC\\V@z@Cp@Kp@Qb@S^Sh@c@x@{@rBqCHEH@FFDN@PEbBBhAt@pFn@zDBt@I^{@rB{A|Ci@~AQt@YnBIlA?d@J`@hA~BPl@?fAFb@lAbFLn@@jEDbAD^Nx@r@xB`@nBH`B?bA]~Be@nCM~@?^Bh@ThBVjAVt@LVj@z@t@`AhAhATXVb@HBAIg@s@qBkBY_@k@aAk@_BWwAO{AA{@De@`AoGFu@Cy@M}AW{@Ms@k@mBMq@KcCAs@BcBC]kAeFOs@Ce@By@COM_@i@aAUk@Uk@CQ@e@JkAXkBNs@b@sAbAiBt@eBb@cAH_@@g@ASs@{Dq@mEIw@AkADwB@[F[^m@L[|@yDjAmEB_@AMGM[e@UW_@[W]y@{@[g@Ia@E_ACQGQS_@s@u@EM@c@J]He@Pu@f@}Ah@uB^aAzAyA`@g@ZSbDoAROFKx@aEZ}@f@eAbA{A^a@`EaD|AsA^_@r@{@lAeB|AeCl@u@\\[^Qb@Il@E`@Mb@U`@[p@{@|@_A~@}A~AcCRWVSfAg@`B]ZAd@Bd@JVJx@d@b@LXBn@A|@Qn@En@Nb@DrA@hDTZAJGBYFyFHuD@kACmACuFI}DSiFMsBKmAS{A}DuVqCyQKm@G??JJXfC|PvExYR`CZtGF|BL~KIfFK|CCbCRjD?tAK~@gCfOKdA?RBPHJJ@JEZYB@AA@AM@HCP[l@i@nEsEdAaAVOLALBLJHLFR`@xGFh@FPLHLBLAt[cK`D}@lFeBp@OxDqAbIgC|@[xDiAdBo@xBi@DBFL@FA@Jh@b@tEj@|Dj@`FDBHlATxArDdYf@fD`@tD@tABh@Hb@HNTPLDJAnF{Bj@OpDoA|@_@nAc@x@]lBo@pEeB`E{A\\I~Ao@fA_@`Aa@lBq@rD{A|@c@|@[l@[lAc@vCsAhSwHd@UVQb@e@l@eAv@{A\\_APk@zAcHr@kDFk@FeAXqL@sAB]HA~@HjJtAnD`A`C^ZJJJVZx@fBjApBzAxB`@p@l@xA`@lAP|@FrAHd@Xn@JJJBJEvAqB`CsCHMWkEU}B?y@De@Ha@z@sCb@gBLu@JgA\\sGpAkU?oBMmCC_CD}AH_BDKHCnEh@jARbAXvInCbEjAdFxB`Bx@bBp@NDNELKJU^_BTi@Za@tCuC^W^QNCjD?n@Kn@UfAs@x@]`Bg@LCN@LDLLzDbEpA|Al@|@^p@tBpFtB~CRRJ?JIFQDUrCgR`@wDXuATo@f@w@~A_Bb@k@v@}AbBsD~@_Bp@u@tAsAvBgBd@Wh@Ih@CfAF\\?LEJIFSBURuCZaDFe@HMJEV@d@LlAl@J@HEJKFMLc@fBoOR}BVkBR]JE\\?bALvAAl@ILIJKTe@T{@XwAl@qELg@FOLKLCLBv@\\tAf@zANNA\\GnDcBf@OZGh@Av@@fARt@PvATp@Hl@?VIb@U^]f@m@l@{@|@_Bf@iA`@uAb@qAN[^_@b@Sh@?h@Ct@OhIaE|A{@v@e@xAgAVGb@B|@Eb@K^[P[zAgF~DwLn@{Bl@mCX}@NY^_@`@UXGd@?J@p@R`@RdGxDrEpCpBtAxApAd@ZXJZBlAEJFDPz@`IXhB\\hBb@fBbAjDh@|AbA`ChBhD~AfCxMlS~JtOzD`GpCnENLT?HIHMRw@Hg@hA_EzDuMtCiJRYLGZ?JGHMTkAHMJCdBdA`CnAr@\\t@Vb@\\zE`C|Ad@bAR`AXv@Ph@RVRxEfEnAz@p@p@b@h@\\n@Zt@rCdIHHJAJKJg@FMJAFF~AvFDLHBHCFKpAcCpA_BxBsCbAqBHEH@HHjAdExApEr@~Az@tA\\b@`@^^ZJFJ?JGP]l@yBDQ@S[gDa@aHSeG@oA@OFCVLRPxFxDxBpArCnB`EjChAx@`DnBLDVBJEHIL_@Lu@JSH?h@b@~BzA~Av@|@T",
      summaryPolyline:
        "}wpqHkq}eCy@cCW@qAlCoEtF}CxG[S_@kBWAi@lDgEbN{GjW}AzE_A|Aq@Owi@ez@_Ae@mHfWcLp\\yCzBaHfDcC|DkDjCqDzDiClFaAlH}E~MiSxT}JpIaE`B{AxA_A|AkA|HcJlP{@nAmDlCqE`IsDrCgAhh@}Bph@m@fSD`N`AtRl@`Td@`EjClNtAvJtElc@~BpN~@nD~JxYbCnF@\\o@|AyCjLUGqAcCq@cGc@cAy^iFaBw@oFiEgLuBkHgDyc@v@eYUgCrB}CrAuM@_JLk@l@wAvEwDhAcPsGEoArI{yALkCGWiIxCoJ`J_@QqAwDfB`FqFfHuCvAuCWaDtC_NbTmCdDkBd@oGq@mAXeBrBsBhGyCxFyDjD}D~A}BhBwEjAcuAtQOq@cLgnCScA_p@uPWu@kAyV_Dw]aIuDs@aAs@uBk@g@_D_AmIe@aAw@kA_C_Fs@m@o@wB}DyNiMoGoF}NqJiD_@q@f@oBnCBgA^q@bB{G_E{EWq@WwBgAoAMB}@hEwIxPe@?}@kA{@g@gDi@aBbAaApDzBhKv@XxI|@xBO~C}AlDmERCLV?~DhBbNkEpKk@dDIrBfBnEFjBzArGLnHdBbHHdDqAnIXrD|@xCbFhG{CiDeAaBcAwDQwCfAuHBoBM}A_BoGMyH{AyGCoBgBkEv@qGjEgK?{@oBaMBcEHw@zDqNe@aAcDuDSsBoAgBCq@xCoKxCuCvD_B|AkGjBaD~IwHjHyJrCo@dAq@zHiKdEgAzErA|CYxJb@VuOQaOa@}IoJyn@Sm@jJ|l@n@vKT|OYhOR`GsCfQGjBTLj@]MAvJoJZ@^l@h@bITZZ@lhAq]XdAjCfUpFfa@`@tDD~BRr@b@Vxo@_Vjg@oSpAkBtA{C`D{Nn@uStL|AxIxBzG`LnAfDb@vDd@z@VAbFsGm@cKnBcIX}BnB_^Q}JTiEhJrAzOzEzLjFh@g@t@iCpEoEjGa@pDgB~Bi@hHtHlAnBtBpFtB~C^RXq@tD_Xn@eCjDcEzEqJfCiC|C_CrEUlAuKb@CrBz@`@OTq@rCyV^c@xDJfA_@j@aB|AaJh@KlCdAzAN`HeC`B?fGdAhB_@fAkAjB{ClBqFn@{@lDg@fL}FpCmBxBIbAg@lH{TvBgIn@y@n@Y|@ArAf@xMjIpFbEnCP`ArIv@rEfBrGlB~EhEpHvd@bs@h@WxL_b@hAi@^yATQpQjJ|IlC~J~IlEjLTF^aARDnBhGbBsCbEeFbAqBPSRJf@jB",
    },
    {
      stravaId: 9114509922,
      name: "Rower #11 2023",
      distance: 52437.7,
      movingTime: 8431,
      elapsedTime: 8715,
      totalElevationGain: 327.8,
      sportType: "Ride",
      startDate: "2023-05-21T14:14:28",
      startDateLocal: "2023-05-21T16:14:28",
      startLatlng: [50.216941833496094, 22.10909080505371],
      endLatlng: [50.216922760009766, 22.108970642089844],
      private: false,
      averageSpeed: 6.22,
      maxSpeed: 11.992,
      averageCadence: 0,
      averageWatts: 80.8,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 680.9,
      calories: 759.1,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "{~nqHyd}eCYMm@s@e@@QIGAq@e@MEu@o@aAk@SIKAK@MX[jAEDICiIcFkCiB_Ak@aDyBcCwA_DqBSKSGIDEJANBvC^pHf@jIIb@q@|BOZIBMEiAeAi@q@e@y@_AuBoBsGa@yAO]GIK?KFKLiA~BsB`CoAbBoA`C_AhCQVIDIAGKMo@e@gBAeAIiAK}@Mc@iCiIc@y@e@m@sA_A}@s@wDkDgAw@WMmAWqBi@gBk@eEqBaB}@_HiDKCIBIHSbAGNGLKBYBKDSXO^{C|JwDjMoBlGmAtEwFlRk@dB_AdCiBvF{BrGm@pBWl@UTm@`@wAfAsAd@iAh@e@RiAn@a@b@qA~B_@f@k@f@aAn@kCfCaBhBk@z@eA~BSh@[vAk@hE_@`Bk@|A_@v@yAhEe@bAwBdCqAnA{A|AmCzCq@n@eAlAe@n@c@b@iB~AcCjBsApAq@h@WVg@Xy@Vk@V]H]PMHmAtAc@l@Sf@QdAWpCIh@Of@iB|D}ApC_@x@g@j@iBxCoArAeBnAi@d@c@t@sBdEq@bAi@j@iAx@g@VG@GGCK?u@NeCJu@ZmBd@{B^yBFa@F{@AkDD}B?c@EaAWcCCoAC?ANBjARlBD`A@xACzA@jEK`AcBnJSvC]nQI|FUhJGdAI`D_@|IWzEa@lJa@rIWhIAPGLKFiAFqBRk@B_H@_D^oAJ_@@}IDeAAyKm@aAQoBq@{GsC{@S]GeSmBuBOkCAwAB[CkA?w@Fm@E{@Sy@Ye@Qg@UgAaA{B_Cc@WYKg@I}Dk@{@KqAC{Ir@cG^KCc@?q@EYGODoBGw@B_@Cc@@MDSCg@@g@EoAAkA@YBs@@e@B_BCcAMsDs@iRoE{D}@{@MMKCIIa@QcEQeCk@iLg@_JIw@Oq@Yi@_@a@_@Y_B}@_A{@yAyA{EkFo@k@a@g@M[Ac@HoB@gAGuAcB_PgByOI}@A}@{@{PE{@GOKCcAh@aI~CoE~AgChAi@XoAf@MDYCKGKKGQIk@_@aJIc@WYOEsAScBc@uBwAqBoAgAu@eAg@aBWuBKmDDeDHy@?SGSQsCqDYOYI[@[HqAv@YL]D[E[Mo@a@oByBa@UuA]UKk@i@_@c@i@c@COR}DNgG?qIBsC_@kLQuMIyABUDGxAaA^Ml@GlBCdAMnAGTEv@UHAz@VVBb@El@M\\WpBsBRMh@UROxAgBRKVEbASJA@ECAUBcAVWJ_@Zm@t@[\\UNw@^wBvBWRMDi@Hg@@kAYYDc@RYD_ABeBPwA@g@DWHc@RkClBe@T[Ds@@mACM@cATe@Pu@b@aA\\KT?z@CCAIJg@FQFEPKj@Sr@_@`@MdAWh@CHEDIBMEeEGoBc@cL?aBg@wHeByUQcB[aAG]UmC_@kHa@{Mm@{JE]WaAaAwIIi@Gs@w@oOSuGEgFBgDCKBcB@MAu@HoGVqGZ}CvBaQLmAHsASa@MG{JeD}@_@{FoB}@_@}Cm@wCc@uCk@i@AUBqA^w@PIAGKCQEcGEwCEqFc@qa@MkGSuSIaFUiRa@{f@GeEMyNQsNIqPDIPA^BhHG|@?lNUJ?HHFP@R?nABlCN~BLpADNJJJFZBp@PrARbAXbBp@xBjAdA\\nART?~@JnBZn@N|BZbDz@tDz@f@FzBf@pA\\bBVrCRdADn@C~@Wl@]j@a@vAmAd@Yd@KZB\\LZTX`@fDnGVXVRZJZFbACpCHdAFp@Lv@XvEzBfCrAxBpAb@Zl@ZbFlB`Cr@vA^FH@LGnBFx@fAtH~AtJThATp@`@t@\\Vn@VhBd@dC~@`@TbAx@B??O_@g@YOUSm@OQ@QHOZA`@F^HWDDDREDG?DKAE?@HOSUC@AC@]MUk@]EMg@Qy@Sy@YUQQU]u@a@wAcDuTIu@?e@FqB^sIJyE?mAEyBc@}H[cHAg@DeBF{@|BwSlAiMdE_VfA_H^cDd@eG\\}C^_Bt@gBHCFBn@`ArG~L`AbBzA`ChAzA|ClDdHbGtBjBtFtEbB|AhHfG~BhB`NhLXZbEhDhAdAf@\\ZZxBdB|EhE`@XbCvBVNhAfAfDvCjHdGFDD?@Q@BMBMOiByAgI}GgIiHqEuDq@q@KeBSuAEcB?UH[Bi@BgAEg@FoAGw@Ym@ImBB[FKPBBOHEX?PELBJCj@?RO`@M`@UPOFBDG\\QJANI^KRMZGJDx@Qf@?TBpATp@CJJVIn@Gv@Dn@EP@`DYx@QzAc@j@MFEJ?l@kAl@_ANYFIJEX]DQT_@FEJU`@e@JKB?DEFUVOt@}ARYz@uCXm@ZuAHSFCP]JGHMPo@f@y@d@cAX_AAET[DUr@eBD[CG@]G]@WBKLSBMUy@KwAIUG[@KZwAb@_CP}AXcBDaBHi@~A{Eh@wBl@sBb@}@L_@f@yBFa@La@BCPq@T{A^mBPcBHYR_@n@w@\\m@lBaETYHCJ@hBv@fAl@F@FEd@}@z@_Cf@eBHCHBd@b@lCxCr@j@PRdBdCh@n@n@j@`@j@f@~@JHZPt@HXL|@x@`@d@r@dAl@jApApBh@bAf@tA|@rCXl@T\\DBF?FCLWNkAZwAl@{BX}@PSHE`A[dAWb@EH@VVzBlCl@jAn@bAVh@bArANZjA`BZRPDvCKnA@d@ClEG`CGpAId@?bEOpA?xDIvAArEM|BCrBKb@GJEVQh@y@p@q@|@kAlAsBpB{D|@{AbAcAbAu@r@o@jCsBf@[ZALFLLTf@~BrGd@xAHd@RfBp@dFZdBnBnGtAvD`AzC\\v@TXTTz@j@l@f@JBD?FG^s@`@k@p@w@`AaAxAiA`Am@XMXId@Id@ATDtAf@f@HJ@v@C|Bg@j@GBDABDFBFb@|DvAhJTbAHFJ@JEPWh@{AVm@~AkCl@k@pAgA\\a@J]@_@Ga@}A_EK_@Ac@Lq@~@_DLq@Fa@FeAPiB^mCX_A`DcHj@eAtBuCn@qAJ[DOAc@aAuDe@_CC[@KLW~@m@~FoE~AaA~Aw@LEDBDJbAvH|AbFlA|FVp@~@xALb@n@xFt@zDp@lEPrAd@nBBTDnB@lDGhFFd@FN\\h@`@^Zh@JHdBr@`AZdBVxALd@FTNFJBN?~ADdCf@bFRhCvA~NVfDHjBGfBc@~HMrCMh`@Bd@FNHLVN|CrAh@^bA~@`Av@vAl@TBp@AjAOlAAbASjBo@X?JBVN`AhAhDdDz@bA`@t@Tl@dA`Dv@tBhArBh@nAdIr[j@pBh@nAp@hApC`DvAzA|@p@t@\\lBr@HFFJ@NAPa@tAg@tAk@hBAP@RDPrTr\\tHnL?XQx@g@zAIb@Ix@_@nMs@zSE`BKpCOzB?NHj@?NKfDYzFE|AIxAK`DAjAKpBA~@KdA?h@MhBAjAMhBEbAEfDIfBUxJSdGGp@?bBATEFAfAMvBE\\KXGBGAqC{F_@m@KYeA}AKCGDK@MLQt@?JvCxEd@|@^l@f@dAbAfBBJBT]fJW~IQzEIhEKbDW|EEtAOdDQnFc@tLSpHCr@EREBWEi@SiOeEg@U_CwAe@_@m@[EI?YF_@Pk@HKJEJ?JF`@VdAz@fAp@~@`@x@NXPBBBHCRB@",
      summaryPolyline:
        "axpqH{q}eCq@oBc@TiA~BmErFeC|Fe@Z{@cD_@_FwCkJaAwAiI_H_BeAsHsBgQwISLc@`B}@X{Mdc@eIbYoKf[cDnCwG|CiC`EoFrEgCxCoBnEgBfKmE|KmRtSkK~IiEdB{A~Aw@tAcAhHgFhKqCdE_FhEiE~HcD~BKiANeC|BwNBmIe@uGZjG?`KoBpLSvCoA~k@sCdq@Uf@gF^_H@oGl@cLByKm@gPsF{V}BqL?cEuAgFyE_GaAmCO_RrAyYMya@}I[w@wBsa@YiBy@kA_EsCeJqJo@cA@qHkEy`@uAcWcZpLg@@WSQ}@_@aJa@}@gE}@uJeGwEc@mKN{DkEs@Yw@JkBdAy@?kAo@oByBmC_AuBqB^uMBeNw@q^~BwA~J}@|AXpASnCkCpAs@xAgB|Bm@uBd@iBnBmAn@}CpCqAJkAYwA^eH\\mF`DkDDiBf@wB`AOlAXiArCmAnB[R]q@{XmCq_@u@cEUmCoBcc@qBuOkAeXAcQ`@aPjDa[a@i@sVuIkM}BiEr@U_@wBmmBsAa~Ax[e@Rn@R|I^lBpFjAbHzCbMfBnQdElJl@lBu@hDiC~ADt@v@fDnGn@l@dKn@bRrJ|L`EHV?hDfDjTj@zB~@lA~G|BhBnA_@w@}As@c@JOZD`AHWJXMDL_@YWKs@q@k@qDqAo@kAa@wAmDkVr@sWgAcWLaDjEab@lG__@bBgQtAgEP?n@`ApLdTfFhGn`BbuA@QKFk_@y[e@_HL{AD_EGw@Ym@EiCf@]pBE`GgClBKdD`@`EO`DYtEiAjBeDtDyEhAwBpByGxCyFfB}EAwBTm@s@cE`AcFz@mIhFePrAsFpAgIdFaJnEdBl@cAbBeFR?xF|FhGlIvBr@~A~A|EfIdBhFn@jAb@WrB}I|Au@hB]|CfDtGjKl@Xfv@iB|DoE|FkKfI}GbA]p@|@dDlJjBxMfGbRr@pApClB|DaFtDeCdBU~Cx@`Fs@fC`QTbATH~AgD~AkC~BsBh@_AEaA}A_EMcAzAcG`A_JzDcJ`D{E`A}BkBaKlIuGlE_CnAfI|AbFlA|FdBnDn@xF~ClQJbQnBlCfDnAdFl@`@j@DdFrClZ`@rGy@zPMh`@Jt@~DpBnDvCvAl@`FOtE_A~HbItDzJrBbEdIr[tA`EzGfIrFvC?`@uBtGDv@h^bj@y@nDS|AuBzm@DlCyB`j@eApa@]zFQ\\MIyD{HeA}Am@PQt@nIrOgAn]",
    },
    {
      stravaId: 9071529203,
      name: "Rower #10 2023",
      distance: 51690.8,
      movingTime: 8041,
      elapsedTime: 8120,
      totalElevationGain: 329.9,
      sportType: "Ride",
      startDate: "2023-05-14T14:33:00",
      startDateLocal: "2023-05-14T16:33:00",
      startLatlng: [50.21694564819336, 22.10903549194336],
      endLatlng: [50.2169189453125, 22.10897445678711],
      private: false,
      averageSpeed: 6.428,
      maxSpeed: 11.132,
      averageCadence: 0,
      averageWatts: 86.7,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 696.8,
      calories: 776.9,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "{~nqHmd}eCI[[Ee@O}As@q@a@SScBeAKAKBIJ[nAGHI@_@Y{GiEcDyBaFaDcAk@kD{BkAk@KAGDCLDvC`@tIh@fH?RUr@[r@Mh@S\\KH]YW]KGWWgA}A_AyB_B}E_AcDEMKIKBIJsAjCeElFgAtB{@|BQXYZCN?x@YxEEvBX`R^bMXhP?hBI~FHzI?jFI`LIbFKfCIjJS~LKbCq@bHENIJM@KE}@i@cAg@sI_FmAm@{@m@uEeFuFmHGGQGQ?IFGRAJDnAAxEE`@?pDM`EOhC[pDOlCq@tJW~BOhAc@zB]tAm@rCyB~I{CdLqGlSiKfYgJbUcDjJaHlQsExMg@dBi@`C_CrLiCjN_@`Bs@fCmF`QcBtGgBxHi@hBeAxBmAzBkGfK_G|JgCvEwC`F}BpEcDfFa@p@Sd@Yz@kCrKQ`AMdA]zEk@tJ_AfNsAzTKpBGpB@nBHlCl@dKTfCPlANt@jCdL~ApGPlAFpADtFDt@T|Bd@nDHlANjNBr@D\\?`@Bd@CX?nBEv@Op@WbAwCnJw@fDw@tFs@~FStBInDKfTEfDwAn\\@x@zA~Wh@bMVbK@dAIjCB~Ah@jLZrET~APvCn@dB@JDFXFVBx@CVFv@BbARr@TnErBt@VrBp@xAXr@Td@HVHvAHVF`@?dAFhA?dAPXAZF`@AlAJd@FJBf@F\\Af@FZFlBVZ@tC^Z@zAVh@BtD\\lBFt@LnBPpG\\lBN~DPd@?rAJ`@Fp@R|GvChCbA~BdAnBbA|J|El@VlAr@xBbAzGpDpBlAhAl@rAh@bBh@l@XbBj@hAd@TD~@TpAd@dA`@l@^jCtBjAbAvB~A`EbDxGvF`DhCHBJ@V^l@h@p@d@rFnEfDhCfDtC~AnAj@V|Bz@pAr@n@^lEnDpDbDJFL@LATQz@mBHMPML]RE\\BXZjAx@vAtALHD@VZ`@XhAl@vAl@hHxCrDrA`Bf@lEjAdAVx@VnEfAnBf@\\LvB`@nAXFBN?zBb@pBPpBJz@LnBL^Fp@Dn@@vBZLF\\F^?lAFpANlAHvD^zFp@^@ZFx@Fx@B`AL|BRnB?nHKV@tCIbCCxAE|C@vHI\\ETKRMXYrEaGr@{@d@a@h@YTG|AKn@Ix@Mv@Wx@_@nDcChBiA|Aq@pAc@fAKxEDx@Cx@KbCi@fAMd@C~@Dx@HrBJr@?jAEl@@~@NpCbA`@Hl@?v@Mv@Qx@g@z@s@h@q@zAuA~@qA^o@`@cATu@l@kCTi@f@w@`@e@fAaAhAm@lAg@r@e@`@_@p@c@FEFQTYHCDLH?b@QZGF@z@]`@Kz@]`@C^Kj@I~B{@hDyAtEaBxB_@z@Gb@BlAObBWxBk@d@Gb@B\\PZTHBN@LAKFBE^Dt@q@|Aw@zDcAfAUl@YVCf@?`AUbAa@p@_@tD}B`@SdD{BbBcAfFyCbAk@HCVAd@QvG{Dv@]ZEZ?lBVfAHrADZAvDNv@I|Ao@PMDK@OYiCSuG@cAGkGEsAQ{A[}DGm@A_@D_@Zq@xCyC`@m@Vg@ZmAXoAbCaNf@wBf@iBN_ADi@@sAKkEG_EQyGCwDDuA`@aIBmBT{Bh@cCz@iD^mBh@kDrAgFdAoClAwBn@{AZcAn@}C^uAnBuF`@wAl@iBl@yAXoARq@`@_AZcAJQLi@HKT}@x@oBH[`@mAVy@Pa@nAiDd@s@D_@^gAHGVALDLJ~CDx@A^@h@L^CLCJAH@PCL@RH\\EZ@F@DHHDb@E^A`@FTAv@St@?BBj@GBD~@_@APG@GRHHTDzAIh@BTLNALEPDR?j@FlAETK^c@BMHuA@]Hq@Bw@DS@[A{BLkBBkDA{@FiA@{BH{A?e@LgFBc@NUHC~AFl@JrAANCf@DLCJ?`@DRHdA?|@F`@HXB`ACxADfA?fADZCd@@VBz@?TBd@ChAFpAArAJd@?`@Hl@@PFJ?z@@XEl@?JAHBX?VFhACfAFj@?`@DFAJSBK?}@DW@MGSBo@GyCAiDMsE@aBHkEFiA?y@AWFm@JiDBQFILBlAj@zAx@dF~BTRjEnBxCxAl@TJ@Jk@b@oFG_EMwEIgAYeBGeACoDc@mFOq@[y@Oq@MiACu@FmBnBu[BIF?jA^`Dx@vBd@~@\\x@Rh@R`B`@h@HR?FCFI@K?]LIZB\\Cz@Sn@GH@FBPRHDH?TGNUPw@BOAOEKUMOQQgAYwCGeE@aDLgELqBZqCRuA?WRe@L_AJ]PGNQLAHSDu@Ou@@YP_AV}AX{AV_AD_@T]Dk@f@yDrCiNp@uDZuA~@qFbAaFD[rBmKdBiJNy@Z_CXaDBwAAQD}B?sAE_AKuE[_IGcEEaJB}AF_A?IQIe@EIEKUWiACc@PeA@O_@k@y@EMHgB[_CWu@[e@]o@q@U[_DwF{@mAyB_C_GuFgAkAeAgAI[B_@Pm@bGaQfCwKZgBN_CHcCZcGNcA`AiE\\eCNcB@cA@iFBaARaE?uANo@?QIo@?QV_BPgCDqAA{@?MHYD]Aw@RaAJgBBE@DSJEJ?b@El@If@E@QIQB_@J_@CUI{@e@WGG?OFEFQr@i@j@e@RW@SCe@QuD_Ce@Uk@c@g@YYUeAk@u@g@yBoA[UuC_BsAo@IKEUCCOJM@[G[OwBy@}Bm@qB]w@QiBWeBOsAG_DEcADmA?OKSa@IYEm@I[KEKAk@@w@LyBFM@[JIAK@EDGRCzAAPKZIHGBa@?u@HU?oGt@a@B_@Ie@Fm@BMDCEQAKD_@D_BFi@FcABcCRs@JeBJE@MTKDw@Fi@@g@D_DNo@HqAFqDZe@@wCT}@B[H}BXo@Dc@HmCVwG^}AFq@HaBLY?wCVi@FcC^iBTkBNwAD}AC]Bk@Lw@FaFNoB?k@CoDQgAMcA[UESIwBo@{A[oAa@uBkA}DgC_DmBqBiAm@YkDmB_Bu@aCuAuJeGcBgAeCwAi@_@k@c@[c@KU_@kB}@iGa@sBOg@Qi@[g@u@e@i@Mg@AUBe@Tm@`@QRKVOf@Mz@Ut@KTMRQLQH]FqA?eAKwDy@_@G_@MkCk@cAQgAM{@SyF_BsAe@sAm@g@QeAu@KES^KCMa@GIm@]eAc@i@]MSGQKq@OSQE]L_@Be@CMAcA[uJuEmE{BI?IKg@Ya@UI?c@YmCoAkAo@iEyB{@g@_CgAi@_@]MoBeAy@_@kDgBu@]EEYIy@a@_@WIAg@c@cCeB_Ay@kAgAkDsDsBsBiImHiBcBwD}DgEeEuAgA}AeAc@a@oBwAwA{@{Ao@c@OE?CDI^C|@GRKBy@SaACgM?c@AICaADeCAk@ESBiCEgNG}SWmOI{BGmF?a@CcBA{@Ek@QkBaAi@_@kAm@eEgCIAe@[eDiBgBiAWMGAQUMGOCOKmAe@}PyEw@]wAaAUGMM_Am@EGAYVoAFIJCHBd@\\fC~AjC`AT@BDFP@R@C",
      summaryPolyline:
        "{wpqHiq}eCo@yBWE}AvCqE|FgDhH_@bLrAvp@IhJHfQ}@xp@KbCw@rHc@FaQuJsF}FuFmHk@OQZ@tHQ`KgCr]s@dEkAhFuGdWqGlSiKfYgJbUcDjJaHlQsExMqAfFiH`_@aHhUuFxTsCtFkOdW}KjSeExGkAtD_C`Kk@`H_Exo@SvHr@vN`@xExGnZR|JfArKLrMLxCChCUhBaDjKeAnE_CjR[~^wAn\\jCni@RpIExGj@bMbAjMv@xB~Ff@xH`D~HtBlOz@rQtBld@tCrAZpOtGpPdI~SdLlSjHd_@|YdAhAtUdRjHfDjKzIp@QdBgDp@AjGlFjMtFdIlCjYfH|SlBbDj@p`@jD`g@e@r@Ql@g@lH_J~@a@lCUpBe@rImFnDuAzIIjHgAlFZlDCrF|AfCWjCcBdEyE`AsBbAaE|@aBhBgBvCuAfCiBd@q@XH`F_BlBY~NwFfHs@bGkAb@B`Bj@KFb@?rCiBpHsB`CYtBaAhUkNjCcAnIyElFZfHRv@InB}@F[YiCSuGKcLw@gJ`@qAxCyCx@uAt@}CbCaN~AaHF}Bi@}Yj@eOT{BdBmHhAyGrAgFdAoC|BsEjBwHlFqOl@aCtF}O`BkEd@s@d@gB|@FbHRtAKzAF|BPlAUhB@~@_@Qf@^NzAInDVbBQb@q@`@mGA{BLkB@gF`@oPBc@XYlCRdDCtFd@xSNfF^rLLN_@FcBY}TNgJRwEHWzWbMr@XJQh@kGUwKc@mDKuFc@mF{@}CQ_CzBm_@fTrFXO@i@LIdD[bA\\X[Pw@@_@k@k@QgAYwCGuDNyJ|@qJl@cCx@o@Du@Ou@@Y`ByIT]l@eFdQ}}@j@yD\\yFBcFu@yWEaJJ}CQSo@KKU[mBRuA_@k@gABgFs@{Ay@eAmA{EeIaMaMeAgAI[TmAbGaQbD_Ot@gOpAmGl@iFFoJRwGNo@IsAh@gFRsEAw@b@mDWZEpAOh@cB@qBw@UNQr@i@j@qAPaSuLiFoCSe@y@DqGwBsGgAyDWqH?c@m@YcBWG}Gd@MXElB]h@}J~@sLb@}Gj@_@\\yYhB{JjA{TvAcKlAuD@cJh@iKa@{K{CsMaImP}IiSeMsA}A}AuJq@{Cm@qAu@e@gBKsAv@]j@_AnD_@`@o@PwCKkQoDmIeCmE{BS^KCUk@}C_Bq@kBuBFqA]mQqIyh@eXkFcEkJoJsLqK_KcKgIgGsDkBm@IM|ASV{BWw{A}@",
    },
    {
      stravaId: 8984887060,
      name: "Rower #9 2023",
      distance: 30373.8,
      movingTime: 4421,
      elapsedTime: 4421,
      totalElevationGain: 136.9,
      sportType: "Ride",
      startDate: "2023-04-30T13:58:50",
      startDateLocal: "2023-04-30T15:58:50",
      startLatlng: [50.21688461303711, 22.10871124267578],
      endLatlng: [50.2169075012207, 22.108938217163086],
      private: false,
      averageSpeed: 6.87,
      maxSpeed: 11.962,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "o~nqHmb}eCBc@Ac@EKQO[Co@QyAm@_CcBk@YK@IFKTW~@KF{AeAwBqAQMQIuBuAqEsCoA_Ae@UaBgAm@[QOcDoBI?GDGJAP@rBRzERxCDzA\\nEAPK\\w@~BGJIBKAeAgAy@eAu@uAo@}A{A}Eq@gCGKIGK?KFS`@_A`BaAhA_C|C]j@i@hAYd@u@nBQVIBKEGKKu@UeAMw@EsAGi@Ik@U_Aq@wBqAuD[o@]g@KIWIUQw@q@i@m@mAiAyBkBiA{@UEeAKeA]oA[i@QoB}@{@g@iCmAwGgD[MK@KHGPO|@GNMH[@KF[h@sKd^m@dBYfAGHK@KEGMc@gBi@_AePcW}A_CaBwBuAgCkHwKgBwCkCkFe@kAWg@COAa@CQq@iC[sAy@aFm@{FMYUK]?s@Ew@]y@g@MKEOGg@SWWUeBcA{MwIm@Uc@Cc@Da@Pi@d@Yh@Ur@k@rCg@bBkFzOy@vCQ`@KJWN[Fu@Dw@?KBWLcAv@wBhAo@`@{HvDg@Lu@Dg@Hg@PUROZq@lB]lA}@jB_B`Cs@r@e@VYHu@?w@MmDq@aAIe@@s@HYHe@Pm@^gB|@YDM?{@CYG{@[qAm@KEK?MDSXm@rDs@pDOj@Ub@QPIDSFWBi@?qBO]@IBIHMd@OfAYdDiAvJYzBOr@GLKFK@KEk@[o@Ue@GM@KDGNCPs@jICPGNGJKBW@y@Em@Am@HIBiAr@qD`Dm@v@i@z@_BlDgAxBYd@OTiBjBYb@Yh@Sz@mAjJs@bEcAfHENIJKBKEIKiBwCa@y@mAiD]w@c@s@aAuAeBqByB{BUOKCK?YDiAZy@\\mAx@c@RWFeAHiCAk@L]Re@`@{C~CORIVg@lBINOHQCQISEc@QIGwAk@yDmBuBy@i@KoEsAoBq@mEmAgAQcEc@MGGGAYJwAPkF@gAAgACc@Kq@eAmDIa@Is@IiBQmIAqB@eCAy@OsBOiAO{AG{A?s@DsAT_DDiA@sAC{AG}@O}@c@yBe@qC_@iDOgCMiL?oBDk@\\}BJuAJuEFwAXsC~@{EViBt@{CdAaD~AyDv@yAlG{Jf@m@z@s@PUf@kA~AgDTo@Fa@\\}FLw@jC{FVu@`@aBN_@rAkBn@oAt@cBv@mAp@s@lAgA~BuCvCaDtBwB|@w@f@cAj@}Ad@iA^q@dC}Dt@sA^mAtAmGVu@`@k@dXkQ`CiB`C_C~HoGtCiBfGkD|@o@XWt@{@bAeB`AsArJoI`@S`@CPB~Ah@NBPA^In@[jAaAHMLe@R_CLc@Xk@hAiA|CiCvGwE|@c@x@[bCw@zHy@n@Kp@Sn@_@vAgA`BiAfD_Bj@Sh@E|BDfAUlDc@`AY|@m@`GiFpAeAlFeDpEuDV[Zm@h@sAd@sAlAcDbBeGfCmHdAmC~@eDxAwF\\iAbCcHxAkDFg@Ai@w@oEE{@Hw@VsAbAaETm@f@cAlAqD^s@v@_AxAuAhB}AZSNElAWp@C^Hz@\\l@NNBlAK~Be@XGD@FT\\xCT`B|BfOfCzObCrNXbCpAbILr@Pn@r@pBnAxCxIvRlAdCnF|LbB`EjEtJxBbG|C|ItAfEh@pClA~Jh@pDFHJ@FIx@}B`@_AXk@`@c@tBaCp@o@z@u@xBwAzB_C~@oAv@}Ad@qAhDyKHQNKxAh@t@b@d@f@~@pAx@bA~@~A~@xAf@|@P`@d@vANx@Jz@JtBHv@r@pBHd@?TG`@iAzCiAxDWlAQzBCxBCx@m@|FC|@@RFPZh@tCnD~@fA~@`Ad@VdBb@f@TtB|Ap@p@|@bAp@`A`BvC\\x@f@nBZz@hAxApAvARXFNRfA`@tDPbDH`@FJRLVHrATxBf@TLJHRXVl@~AvDp@xAz@xBZf@HHVHjEbAb@LJF\\b@fAxB^f@HRBd@SnEOp@c@r@mRtRgEnEgAdAc@^k@f@E@}@bAYVUZaAz@s@r@iAlAEJk@l@yArAYLSPo@dAgAdA_FrFg@h@}G~Hc@b@{ChDwAjB{BfD_DpFcAzAcAdCSp@EZ?FBLDFZPvCtBPX\\rAPpAApA`@rEHhAA\\LnBBFBBb@?DFBJDvBPlDElACX@NEX@HBHJB`@\\ZLz@f@BDTd@NFbDvBhGfEnFfDlG~DLDn@J^NH?FEDOJw@FMJGJ?vA`ArC`B|@^^DNRBV",
      summaryPolyline:
        "}wpqHoq}eCi@kBUGUXiApBuEbGsAlCw@nBSLKEs@mDMyBUwAiCgIc@_A]g@y@e@oDiDcEgD{AQ_EkAiRiJWJ_@~Au@R[h@{Mrc@GHWCk@uBi@_AePcW_EwFuAgCkHwKgBwCkCkF}@sBIcAmA}Ey@aFm@{FMYUKqAEw@]gAs@Mw@k@m@aQ{Ky@Wo@@a@Jk@`@k@dAaBzGkFzOy@vC]l@s@VyBH{AdAgDjB{HvDeC\\g@Pe@n@oAzD}@jB_B`Cs@r@e@VoAHeF_AgBGmAR{DnBg@DuAKeDoAa@^aBdJe@nA[Vk@J{CO]@SLMd@OfAYdDiAvJi@nD_@VgBw@e@GYFK`@s@jIK`@SN_CEw@LiAr@qD`DwArB_BlDaB~CsCdDYh@Sz@iAxI{B|NOZKBUQqBeDgBuEaAkBgDgEyB{Ba@Se@DcCx@mAx@{@ZoEFk@LcAt@{C~CYj@g@lBYX{Ae@qK{EwP_FkGu@UOZ}I?oCOuAkA}DQiBWsKAqHOsB_@eDGkBDwBXoE@kDQyBqAkHk@}FGaCIkMl@iFTcIXsCvAeIf@uBlB{FdAeCrAeCpFoItBwBfCsF\\qA\\}FLw@jC{FhAwDrAkBdBsDv@mA~B{BvGwHrDoDxBkFzEcI^mAtAmGVu@T]`YcRpB_B`C_C~HoGzMeInAsAbAeB`AsArJoIbAW`Cp@p@Kn@[tAoALe@R_Cf@oAfFsEvGwEvB_AbCw@zHy@`B_@hFqDrEsBfD?tFy@`AY|@m@rIoHlFeDdEiD~@uAfCwGxByHlE{LvDgNbCcHxAkDF{@}@yFAg@Be@`BgH|@qBvAcE`@s@x@}@pEwD|A]p@CzBr@l@DzEw@HV`@lDnCtQjGn_@jBfM^bBbCjGfL|V~Ot^xBbGrFdPh@pClA~Jh@pDRJFIzA}Dz@oAfDqDtDmCzB_C~@oAnAoCvDyLPYFCzB|@f@b@fDnEvBpDt@bBZfAPlAXbEr@pBHd@Gv@iAzCiAxDWlAQzBGrDm@|FC|@Hd@pDxE~BhCd@VdBb@f@TfDnCnBdC`BvC\\x@bAjDzCpDZh@t@|FPbDPl@j@VlE|@`@Vj@fAhFrL|GlB\\b@fAxBh@z@Bd@SnEOp@c@r@uXdY}CnCmBvBqFvFyArAm@^o@dAoIbJeNxOkEfG{E`Ii@hAm@`BMz@HTrDfCPXV`AVbBApA`@rETvEFJb@?HRVdHKzCh@b@",
    },
    {
      stravaId: 8943654339,
      name: "Rower #8 2023",
      distance: 57224.6,
      movingTime: 8798,
      elapsedTime: 9143,
      totalElevationGain: 275.5,
      sportType: "Ride",
      startDate: "2023-04-23T12:12:15",
      startDateLocal: "2023-04-23T14:12:15",
      startLatlng: [50.217044830322266, 22.109182357788086],
      endLatlng: [50.216922760009766, 22.10895347595215],
      private: false,
      averageSpeed: 6.504,
      maxSpeed: 10.76,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "o_oqHke}eCZI?JADKMGEc@EgAYaAg@mA_AmAu@IAKDGHKXSr@EJI@ICqCiBoCaByIaGwGaEeB_AK@EHGp@@pAFnBp@bKLhBJz@ATGP_AtCKFM?KEs@q@W[y@mA_@q@c@gAq@qBmBqGGMKIK?KDmA~BkB~BoBhC{@fBaAfCQVIDKAGIQgAOk@GII?EHEJKjAYnAyDjMcEbPsBtHiAjDs@|Ae@h@QbA[|@oExK}@rBu@vBSz@O~@QtAGtAUrOCpHG|AEpIDzHCbFQnF]fGWbDSdDi@zHYfCq@fDeGxVwAdFsAlEg@pAsBxG}CxIUj@w@|BqF|NuFnM{@vBqDrKi@vAyDlJaCvGoCdI]hA}B|KaDnQu@tDW`AeGfRm@~B{CrMk@pBYp@{B`EyDzGeCzDgBzCqDtGqCvEkElIsBxC}@xAYp@Up@oCfLMt@UpBy@dLiChc@g@nHCdB@bBJlCl@|JVnC^rBbF|SZlBDdAFpFDvAt@pGN|BVfUA|@Kx@YfAs@tBmBxGo@rC_@~BiAjJW|BGdCO`WE|CYnHy@hQAl@D`A`BnYf@dON|GG~B?|AHrBr@dODfAF|GCPGJUJeBBs@NeGjCqCpAe@NmFnCoDxAoB`AYHg@HaAFaA@oCLoCF_EPiDVmHz@mBFuCBaALqAj@cEvB_FbCwItEmBhAaAp@c@b@_@h@}@zAsErJ_E~HsEnJqD`HsBrEsDxHaAfBSTULKBY@kAO{FgAeKiB_HcAw@OUAQGy@Mu@GcDGiBJeARkJzBg@F{@AqAMu@CIFGHQj@Uz@Mp@MdA]pEi@~EGHIDm@HQNWNm@IcBFu@Ii@Ky@ScBq@w@_@[SqKcIa@Uc@OoNkCaFgAaD{@yQqEyMeC}Aa@aK}CgDy@qGgA{B[wE{@g@Eu@E_A?YD{@R_@Pa@VaBjAsAjAuB|A_F`E{DvC}DfDiHpFiMdKm@`@uDzCwAfAkB`BWL{@n@k@j@oDlBsBtAo@\\gC`Bc@ZWL_ErC{@f@gB|@iE~BGHGZ@ZLj@Ff@@HIROHk@Fa@T]ZAJ@JKLkDvBs@`@sBrA{Az@k@b@u@r@_@j@Qh@c@zC]vC}@dGYtA[t@OTWh@eBhCWd@}@nAK\\C?EFeA|AIFk@dA]h@QZY\\Wd@Qf@C^Dx@HPFZHLDR@ACG@BADGEI_@IIEEwAc@WWI@c@s@[aAG]aAuCs@aCs@sBa@}A?Q@Gh@{Az@iBZaAxAeD\\}@@MEU@CGHNOBs@DKAs@MkBg@}EYcA}@mBeCwEyCgGi@}@aAqBc@gAMg@Ii@EcAMwFu@gJi@qEEaA@yAEsDEyKEuAKuAq@wGg@eG[}I@uANkFHkFNyBBo@?{@VyIAuAEw@MiAq@{EMiAk@}Cw@mFWuAS{CAaAs@{LKkDIsAS_B{@{DKgAE{@CoEBeBJcBbAwINaBDsAF}C?e@Gy@Ms@M_@qAwDoBkFi@eBs@mEiAyJYsBiA}FYgBKcAOmCQqAy@cDc@iAk@}@u@k@wAw@i@Sw@Qm@Uy@_@sAaAsAkAaAo@UKm@Ka@?gABgDTg@KGGCKIeK?cDBmCZgNNaDt@eJb@qDj@cDxFoVZ{@n@s@nEkEzFaGbBkBr@q@FSASUw@IUIIgAoCy@cCC_@?MFaAFgBEeAQcAq@yBOeA_@yKkBub@}Cko@eDav@aA}R{@gNc@_GI}Ci@mJ[kIm@uKk@oNsBcb@KiDAgCDoF?mGFwC@wCC_AEi@My@Su@gAoCyAeEm@}Aa@qAiAaDg@oAy@cCiAuCw@{ByD_Kq@wBgA_DsEeMc@sAmDoJyFcPkEsLu@qBAO?MNWxAkAx@{@^}@Ha@Ac@[mAE_@@QH_@Zc@rByBnA_Bf@gAr@sBf@yBX}BXiDd@kGBkACc@Ia@qAgFc@qBEg@@SHoAPs@x@qBXa@vCoD`@q@Ti@J_@Ju@z@iIt@oErDaW`@}BRq@^{@hAaCjDkGL]DQBg@CoAkBeUK_B?w@Hc@\\aAbAmBrEuJNKxAOtAi@lAk@lImDlDaB|I{DbB{@vCoA~Ay@r@o@x@}@pCgD~@eA~@}@d@WzBu@t@OVAPBfAZJ@`@N^DZ@TCTG`@St@u@r@{@b@q@r@wAdJqS`AoBT[t@w@zBsBTMTKhBe@nCk@|Eg@vAK|@EpADRBdABXFl@?l@DbFLzA@t@ElDc@v@Ih@Kl@_@Z[dAqAv@{@bAu@r@[jEcAdAYdCk@H?fBg@hB_@d@AdALv@P~Cj@^DpCj@jN`FxDvAf@Nd@RpC`Al@NrDvAd@VlAbAvNlMtBbBh@^`AXnBZnAJlHx@jBXbAFtGChCCNAn@@ZENBbA?f@CL@LEf@A^GF@h@IL?jCUlBUtAKh@G^CRBNA^GJD@JDDx@G^@fCIZNHTNNx@HP?PSVaAFCn@El@Br@EjA?v@C~@@v@Eh@DJVLh@FJZLV@TGVe@La@FE`@Gp@?JM?KBCXCV?tEg@tHs@xBQjFi@lCSfCYhE]vAQzBOlBSv@GjTwBx@EjAOb@CfBOx@Kt@OpC_A`S_IvEaB~BaA~CgAjHwCZIl@YxAi@bAc@nDqAbG_CfFiBv@WjAUf@Cp@@fACz@?tJLp@BhA@nABjC?j@@PBpB?hAHpABZ?JCPFH@tC@NBnBFbDGbBTpAVpAb@f@L^FjAZl@JzAf@p@NzAb@z@RbCp@`E~@rCz@dB\\`B`@lI`ClB\\tAJl@BxAMZBLDT`@TJPCNKTi@LMFEZEZAPDjAHd@Jd@LbAb@pA`AZX|@jAZj@x@bBNf@BLCl@@\\@LLTHFRHHA`@KHB^TbItGzAxAvChC~DbDfIjH|DbDrGvEbAl@PP\\RpA`AfBjAx@b@XZt@h@xCtBpAx@bAt@~@l@XVfC`Bp@j@xBxA@LQz@INoDvPi@|BaAtFgAhFAJ@LL`@RXFBNTZZNVNJF@TMFI`@yAFGJ?RHnAt@nDdBxBlA|DlBx@XjCn@|AZZJjGlFp@`@NLdAfAp@fA`@bAbA`D~@`DFHF?FELWF_@FGFEFBjBbGF@F?NM~@mBn@{@lB{Bh@u@T]`AoBDCN@z@~CtBpGh@hAf@x@v@bA`A|@HDH?FEPSJ[l@wB@c@GgB_@kEc@kJ?sABk@FIzB`BlAv@xDlCjBhA|MtIRDf@HFEFIR_ADMJIJELB`CdBdAl@j@XHARJ~@VH\\CB",
      summaryPolyline:
        "}wpqHoq}eCm@mBWIURcApB{EhGoCfG]Ea@sBW?k@fDyDjM_InZuA|DeA~AYvAaHvPiArDc@jDW`NUrYDnIKjI}B`_@YfCe@bCqG|WwAdFoFxPkFbOqF|NqHfQqDrKcFdMqG|Q{CfNwEdW}GhTuFdUuCrFkV`b@kElIqDrFo@bByChMsAjPqDxl@CdBLpFdAlO^rBbF|SZlBRnKt@pGN|BVfUMvB{DvMo@rCaChR]d`@sAxZBnB`BnYf@dON|GG|EbA`UF|GK\\oD^e^bPkSz@wMrAeIXuNfHeM~GeBtA}AdCyWdi@gHlOaAfBi@b@qBIaSqDoNsBmGByMvCcESc@|@c@lBuAvNiBx@gEKgEqAsAs@qKcIeAe@oNkC}]uIyMeCgSyFmSeDuBEuAXcDtB_aAtv@sI`FcK~GmJdFOd@VnBG\\}Af@]Z?VKLoLhHaBvAg@v@_D`TgA`C{D~FK\\yAlBqCxEOl@?t@f@`BKCYo@wAc@a@Ui@_AiF}P@Yh@{AnEoKAg@GHPSDoBu@iIYcA}@mBiI}OmBkEUcCMwF_ByPU_YeBsR[}IZmPNyBZeMAuAsAgL{BaNiAySU_GoA{GQcC?uH~A}OLqFG_B[sAkFiOs@mEcBmNcBeJm@cHy@cDc@iAk@}@u@k@wAw@iE{AgDmCwA{@oAKoFXg@KKSIiP^uRdAgOnAuIxFoVZ{@zNaO~CqDWkA{AoDy@cCCm@NiDEeAQcAq@yBOeAkCoo@}Cko@eDav@aA}R_BgV}GayAMqHNmXIiBa@oByUmo@}_@{fANe@rCgCh@_BAc@a@mBJq@~E}FzA{Df@yBr@gHh@wIMeAuByIC{@HoAjAeDpDqEv@{ArA_LjGoa@r@mBtFmKRo@?wBkBeUKwCf@eBpG{MTSxAOtAi@bg@}TlBmBpEmFdBuApDeA~Dt@p@Av@[lCcDzMyYjAsApCaCnG}AtHs@~Sd@zGs@vAk@xCiDvBqArRqEjBJhKnBfb@fOrBzAlRpPjBx@|SbCdSKrRaBRV`FOZNXd@x@Hb@SVaAFClKOh@D`@lAr@NTGd@gAzAMN]jxAcNreAga@jJwC|EErj@~@bDGtDl@hr@rQbCVbDEb@f@^JVOb@w@~@MbCZhBp@lBzAxAvBhAjC@xANb@\\Pj@Mh@X|f@lb@hk@v`@OhAcFdUkCjNVx@nA|AVLTMh@cBRGjQ`J~HpBrKdJrAjCbCbIVBTw@VIjBbG^K~@mBfEmFjA{BPUN@n@`C",
    },
    {
      stravaId: 8901450766,
      name: "Rower #7 2023",
      distance: 31382.1,
      movingTime: 5216,
      elapsedTime: 5686,
      totalElevationGain: 280.2,
      sportType: "Ride",
      startDate: "2023-04-16T12:27:43",
      startDateLocal: "2023-04-16T14:27:43",
      startLatlng: [50.21770477294922, 22.109508514404297],
      endLatlng: [50.216915130615234, 22.108943939208984],
      private: false,
      averageSpeed: 6.017,
      maxSpeed: 11.75,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "scoqHkg}eCc@U{CwBIEK@GFa@rAAR@JPVv@l@hC`Bx@ZdHlBrH|B|BlAnGvDlKfG~@f@^Ln@Lr@BhFFzAAzED|HR`MHjBDrB@jFH~BCN@lBDzCCLBtA?|@BFE@MCIGAc@D{@AGAQUAIBkAAQBoABUR?j@RlBX|AFn@FFG?IAeCVk@NUv@{@nAmAbAmAbAkBr@eAh@o@^Yz@SVMDANLF|@r@zFHxAAnCB~@BLFHPHR@FBDHDTElADLFJnBn@f@XxCdC|@n@jA~@\\R|@r@h@f@j@n@`C|BTXNJfAdAj@p@bB`BbGjFlAlAr@j@j@r@tFxFdBvAxB|A`B`AxCtAlGfDnKlFzM`H`NvGpBz@fAXd@B`@Eh@IFBJTHn@DNPV^XpBx@dB`AJBZ?d@ZzB`Ar@V~A`@~C~@jATvAPnB`@bCn@nCl@v@JhAFr@?XIVO\\a@Pi@d@}BL]RWnAu@LEJAJ@d@HVHVNTP\\f@N\\r@pCn@fDn@zEPb@HN|@v@`Ap@|@`@bCbBnC|ArExCjBbAvBpAfIdEnBfAtCfB`DdBn@b@p@^jKvCl@FdCN~AFhAAn@ChA?fCIn@E|@SXCVAh@Ff@@lBGlAKtASpAQN?r@OnAOrAGdFc@P?vAIjBGjBIzG{@`Fc@nDOzAOlLw@hAOHCRS~AK\\Kt@GnHc@^@VIPBDCVG\\AHBTCl@Bj@AzAW~AKz@MdBMPMJUJkBBIDG^EHElAIv@MnBGPDFFDNDx@P`@LPHDfBBnAAdA?bCLlBPdC\\vDv@nAZhDhAR?DBTMDD@^JNl@PjDjBbE`CpFlDfCvAf@\\^LRDT?TCRIXW\\c@JSDYJKL?NDlAf@RBR@ZGL@JCFD?Ra@LGHGJC`@@RDNZb@Fd@?f@OzCMx@U`AEL]XGLARFd@Xd@DNDf@SjGCzFC|@S~BW|B{@lDSnAi@dLMdBUjAo@tCyAlG}@lC{@|ByBjGu@xBAN@HJTxApAnBpBvBnBtDtDf@l@f@v@xDrGh@n@lAz@x@VdEn@TJPRHb@DFb@DFGJm@HGr@Gr@BZUjAi@pB[fAINEJOFc@Ze@D?FBHLJDL?JCJ??EyJzGE?KKM_AEGs@Kq@FQASIOYW@UEEBWCuAUiC_@o@Sw@k@q@w@wD{GaAuAuAuAyHqHmBoBEKCO?ODQdGwPXaAbCuKX}AJoAh@sLTyAx@oD\\qCN}A@e@DmHVgFA_APaA?QIq@JgAPcADc@JaCAyAF_@Bq@Aa@CMGIGCGAMFYD_@Au@Uk@YSCSLEZEJ_@f@QNo@Tg@C]Ke@Wo@e@{@c@uAaAsEqCuDyB}BoAi@Qu@c@OM?GFKACG?SFO@uCcAqBo@{Co@aBYyBSIC{BKkAAgEB]COSEMQu@?i@EIIGU@MD]?QDg@ASFYCc@F}ADGJENGtBEPIJIFcCP_Ff@m@JOEGCGUDeAAg@JmB?qAKaCKoACaCMiAOi@C_@GWScCALN|@@TP|@Fr@Nz@B`@DVAXBvAL~AHtBA~ACh@CLAbCI^GBkAEM@KHYE_@J}DLiBRo@By@LsAFKBWXwADmAJwAF]DkIh@i@BUDk@@sAJY?WDUJq@DoBVmBTeAFg@JyADgBNkCJe@FuCNgCTyC\\e@J{BZg@DqBHa@?{AIeARaAJeBFm@D_CDsEMc@KgAC_@EoA]uDgAs@Qy@WuAs@qBkAqCgBiBeAs@g@_JsEmCyAcDmB{B}A{GiEuAm@u@k@i@e@OQUa@[mBm@gEScAw@iDa@y@_@a@SKm@Si@A]Fw@d@YVYj@e@zBKXU`@YXSH_@Fi@?eAGg@GgEcAaE{@aDg@wIeCqCmAo@IWIGGg@e@aAi@}@_@e@[OUMu@GMIIEAK?q@Jg@Am@Ky@[q@_@sKcFaHuDwBaAaAk@m@WqCyA_Bw@wAw@SI}A}@i@WYS[ImFkCwC}AcBcA{CeC_C{BkFoFgEwDyAyAw@o@iEeE}B_CcCaCmCyBiFwDyBiAc@QSCGDGXAlAMRG?SGe@KkACaUEaFGkD@}JMiHE{JMmHEqDGmIEaBCs@Eg@Im@YkOyIiBaA}AaA{BkAmGiBgBi@uEqAeAa@gEkCCYJo@J[FKHEJ@vCjBfB~@zA^FR?J?EAH",
      summaryPolyline:
        "_nmqHwg|eCrVZl[Z~BCzLJFE@MKK_BBGAQUAIBkAAQFeB~@RlBXlCNFQAeCVk@fAqAnAmAbAmAbAkB|AuB^YxAc@NLF|@r@zFHxA@nEJVl@NDHDTElALXnBn@f@XxCdCdFvDtMtMdKdJ`HlH~EtD`B`AxCtAxb@vT`NvGpBz@fAXd@BrAKJTN~@PV^XpBx@dB`Af@Bd@ZzB`ArHxBbDf@bK~Bv@J|BFp@Y\\a@Pi@d@}BL]RW|A{@V?|@Rl@`@l@dAr@pCn@fDn@zEZr@|@v@`Ap@|@`@fNzIbFtCfIdEhOxIjKvCrDVhDD`GMfC]hBFlBGhKqAxHk@`I[|N_BnDOhOgAhAO\\WrD_@nIa@VIPB\\KvC?zAW`Gg@PMJUJkBHQnDc@nBGXLJhAP`@VV|F@pF^dC\\vDv@xFdBXBTMDD@^JNl@PjDjBtLnHnEbCh@Dh@Mv@{@JSDYJK\\D`Bj@hAGFD?Ri@VGJC`@Fb@Zb@Fd@ObEMx@U`Ac@f@I`@Fd@^t@Df@SjGGxHS~BW|B{@lDSnAi@dLMdBeA`FyAlGsFvOu@xB?XJTvNhNnAdBxDrGh@n@lAz@x@VdEn@f@^Nj@b@DFGJm@HGr@Gr@BZUjAi@hEk@JOFc@Ze@b@Vd@EyJvGQKSgAs@KcADSIOYkAC_Fu@o@Sw@k@q@w@wD{GaAuAoKgKsB{BC_@DQ~GyRbCuKX}AJoAh@sLTyAx@oD\\qCN}AFsIVgFA_APaAIcAb@oDJaCAyAF_@Bq@Eo@OMoAHuBs@SLKf@q@v@o@Tg@CcAc@kQwK}BoA_Bu@OMDWk@HgGsB}FiA_Gc@qHAUa@Qu@?i@OQiDNaCLMZGtBEPSRqKdAOEGCGUBmBJmB?qAWqECaCMiAOi@Kw@ScCALdAzH@pBL~AHtBIvCAbCI^GBkAEYJYE_@J}DLgHl@KBWXaY`Bm@P}JfAmI`@cIl@cJjAqBH}BIgC^sGRsEMc@KgBIyHwBoCkAaLaHmNmHcDmBwKgHuAm@u@k@i@e@e@s@}AyJw@iDa@y@s@m@m@Si@A]Fw@d@YVYj@e@zBa@z@m@b@iAFmBOiK_CaDg@wIeCqCmAgASo@m@_CiAe@[OUMu@QWkBFm@Ky@[eMcGaHuDeQyIaDiB[ImFkC{FaD{CeCkJkJyIaIkMgMmCyBiFwD}C{A[@GXAlAMRG?y@SkACoa@K_y@u@",
    },
    {
      stravaId: 8865887468,
      name: "Rower #6 2023",
      distance: 23861.7,
      movingTime: 3747,
      elapsedTime: 3934,
      totalElevationGain: 128.3,
      sportType: "Ride",
      startDate: "2023-04-10T12:22:24",
      startDateLocal: "2023-04-10T14:22:24",
      startLatlng: [50.21696853637695, 22.10905647277832],
      endLatlng: [50.21693420410156, 22.1090030670166],
      private: false,
      averageSpeed: 6.368,
      maxSpeed: 9.73,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "__oqHqd}eC?@CICQGK_ASMIKAaA_@_@S}AkAm@YK?IBGH]rAGHI@][cAq@eAq@yAcAgDuBcEqCuCeBkD}BiAo@MKGBE\\?v@DxAXrG`@pGNdBC`@e@tAWbAKFM@MEWSm@k@oAkBc@{@k@{AgC{IGKGGI?IDQRq@nAc@n@q@v@oCpD{@bBmA|CGHSLICGKO_A]_BQgCW{AgAuD{@cCYs@Wa@OS]K[We@a@a@e@m@k@yAkAaB{Aq@i@a@My@OoEoAcEoBmE_CcCiAy@c@UIK@IDGNUbAELKFY@KDIHQZ}@xCgBvFmAjEcDtK{@zBMn@GHK@IIm@uBWk@]c@{DiGoKkPuAqBu@_Aw@{Ae@y@kFcImCgEw@wAiBuD}@wBEy@w@wCYuAi@wC[eC]iDAIMUUG[@q@KYGOIMGYSQGOQMCEECS@YCMk@e@wIqFaEoC}@e@i@KUAi@Hg@T[X]p@K\\o@bDMf@wAnEwCrIsApEQ^KLMFg@J_BBWFWJgAz@aAd@cDhB}Ap@gCrAYJYFyAJWHYLSP[l@aA`De@hAsAtBe@l@e@f@_@XWNc@Lc@AWCwE{@}@Gs@@e@FYFmAh@aBz@a@JK?y@Am@IoCcAIAI@QNMXmAxH[hAUf@QPKFK@wA@kBOSBSLOj@k@hGeArIYpCKb@IJKFK?uAo@UGc@GWFGJKv@MlAGtAQvBGd@GNWRg@Ao@Ia@CWB_@HoAr@qBdBuAtAaAzA]p@{BdFWb@a@f@_B~AY^a@`AWhAmAlJoAvHW|BMd@IJKFKAKG{@{Au@iAi@oAkAaDe@}@cB_CkBuBiBiBa@QWBeBh@i@VkBdAcBPi@A_BBi@LqBdB_B`BU^IV_@zAIXONQDq@YEEkAa@cCmAoD_B}A_@_@McBg@EEqDkAu@ScAa@cBa@_Ea@q@ESGII?q@RgFDiD?_@MuAgAmDIg@Is@MgDOeG@kGEaADo@IQAYUuAMyAE}@AsBBm@NqBAH@ELiCAuCWaCq@gDu@eFMuAM}CGsMF}@`@uCF_BJoEL}AR}AvAmIb@yBlA_EvAkDVi@fAoBrB}CbCwD\\c@fAeAh@}@HIJCr@EdAOZA\\GXAdCYdCM`AO`AUxQeHrD}AnFmBhAe@~HwCpAk@~B{@j@[h@OzFwB~H_DzEeBj@Ql@Kj@ElB?`AFhFDdGPtA@\\Df@BhEAtHJ|@Cn@FFC`AFlA?nCHbBPzFpAlF|AbB^vI`CvDx@jEhA~@RfGdBhARnARx@FlAAt@GT@HBZ`@HDJ?TGJETa@ROl@Gp@@l@Hv@Nh@Nt@^z@j@x@v@ZZr@dAz@fBRl@BPAz@BRL^HHJDL?d@KJ@d@\\lBzAzMnLtGrFjBdBzIhHnHfFtAbAhFlDnLlIdElCbBjAFF@TCJeAdFyArGKf@AZDJHFhB|@jE|B`C~AHL?VWdAy@xF{@fF@JTR`GnCn@T|D~@~@ZVL|AhAlAjAdDjC`A`A\\h@Vn@jApDz@~CNr@PnCn@`DJXHBHARQXi@n@mBhAyBvAmBpB}BXc@x@eBFGH?HDFJt@zC~A`FTn@p@rAz@pA^b@r@n@THJCHIFMx@iCDc@Ew@Ie@SwBS}C[kGAkCB[FIJ@\\LHP`Ap@fHvEb@ZxD`CvAbAzEvCxAdAH?DG\\aBNWJAHBjBpA~A`Ar@Zl@L`@LHN@REC",
      summaryPolyline:
        "_xpqHwq}eCi@cBQGIDQRkAtB{@`AyC~Dq@tAmA|CQPIDICGKO_A]_BQgCW{AgAuD{@cCYs@g@u@]K[WuBsByAkAaB{Aq@i@{A]oEoAcEoBmE_C}DmBUIK@IDGNUbAELKFe@FIHQZ}@xCgBvFmAjEcDtK{@zBMn@GHK@IIm@uBWk@]c@{DiGoKkPuAqBu@_Aw@{Ae@y@yJkOw@wAiBuD}@wBEy@w@wCYuAi@wC[eC]iDO_@UG[@q@KYG]QoAw@CS@YCMkA}@yO}J]Qi@Ki@@_@Hg@VY^Ud@K\\o@bDMf@wAnEwCrIsApEQ^KLu@R_BBWFWJgAz@eFnC}Ap@gCrAs@RyAJq@VSP[l@aA`De@hAsAtBe@l@e@f@w@h@c@Lc@AoF_A}@Gs@@_ANmAh@aBz@m@JgBKoCcAS?QNMXmAxH[hAUf@QPWHwA@kBOSBSLOj@k@hGeArIYpCKb@IJWFkBw@c@GWFGJKv@MlAGtAQvBGd@GNWRyBOw@LoAr@qBdBuAtAaAzAyCvGWb@a@f@_B~AY^a@`AWhAmAlJoAvHW|BMd@IJKFKAKGyBqDmBeFe@}@cB_CkBuBiBiBa@QWBeBh@uC|AcBPiC@i@LqBdB_B`B_@v@i@tBONQDw@_@kAa@cCmAoD_B}A_@qJ{CcAa@cBa@qFg@SGII?q@RgFDiD?_@MuAgAmDIg@Is@MgDOeG@kGEaADo@IQAYUuAMyAE}@AsBBm@NmBLiCAuCOsAMcAa@gB_@}B_@qCMuAMsDG}LF}@`@uCF_BHiDNcCVqBrAyHh@iCnA_EnA{C~AyCrB}CbCwD\\c@fAeAr@gA~I_AdCM`AO`AUxQeHrD}AnFmBhK}DpEgBj@[dHgCzOeGhAYz@IlB?fS`@dAHhEAtHJ|@Cn@FxGJpBRzFpAlF|AzL`DbMvCfGdBnDj@zABjAIT@HBZ`@HDVATKTa@ROl@G|@BlARt@Rt@^p@b@p@j@l@n@r@dAd@~@h@tABPAz@BRL^HHXDd@KJ@d@\\lBzAzMnLtGrFjBdBzIhHnRxMnLlIbGzDl@d@@TCJ_DxNKf@AZNRtHzD`C~AHL?VWdAy@xF{@fF@JTR`GnClFtAvAh@|AhAlAjAdDjC`A`A\\h@Vn@jApD`AnDHb@PnCt@pDDHHBHARQXi@n@mBhAyBvAmBpB}BXc@j@oAT]RDFJ`@dB",
    },
    {
      stravaId: 8819774203,
      name: "Rower #5 2023",
      distance: 11218,
      movingTime: 1775,
      elapsedTime: 1844,
      totalElevationGain: 45.8,
      sportType: "Ride",
      startDate: "2023-04-02T13:55:11",
      startDateLocal: "2023-04-02T15:55:11",
      startLatlng: [50.216957092285156, 22.10910987854004],
      endLatlng: [50.216880798339844, 22.1090030670166],
      private: false,
      averageSpeed: 6.32,
      maxSpeed: 9.678,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "}~nqH}d}eCDGIMm@IqBu@w@m@iBiAUKKBIH_@tAEFOCyCqBeLmHkAy@sBoA_@QkBmAkBcAIAIFELAzB^|Gr@dKANSh@m@zBKDI?IC]Y}@_Ay@kAc@u@Um@kB{F{@sCOUIAIBSR_AhBoEtFaAfBmA~COTGDI?MWk@cDMcCYyA_CiH]w@Wc@oA}@q@k@uA{AyAqA}BmBiB_@cF}AgEuBaEwBw@]{BgAIAIDGJS|@MZIDa@FKFGHOZgD~Ke@vAkA|DgCpIGHGBICgAs@QOU_@i@_AcSuZu@wAcAoAyBmDcF{HaBoCq@uAoBkFk@cB}@yDa@aCo@gF[cEa@cE?Y}@kJgBySg@yEGiB?u@FW\\k@?MC?PDTLFL^\\\\Rv@v@FDNGj@b@n@l@bHbGzAtArD`DbDlCrBfBnEnDfBnAf@`@dDvBdFpD~BxArCxBx@h@fEzClHbFDF@N}CvNIh@A\\BNPP`FjCjC~A~@p@FH?ZOt@_@zBM|@[~A[nBOtA?ZFHRLt@ZvC~At@ZfBb@`Cp@r@PXJlBfBtD|Cl@d@z@v@h@z@`@dArAbE`@vAJb@Jv@XxCb@zBJVHDH?RMP[v@}BjA{BlEwFn@kATg@FKHEH?HFdA`En@pBr@nBp@xAb@t@d@n@n@n@h@\\H@HAHIz@iCFe@@Qe@sFU}DUyE?aCHSDCTHb@\\`Ar@|DfCd@^r@b@~@p@rEvCt@`@xBvAh@`@`B`ATFJ?HAHGFIDQJw@FMJGL@l@f@bC|AzAp@~@TFFBH@PB@AC",
      summaryPolyline:
        "axpqH{q}eCe@}AIGIAIBSR_AhBoEtFaAfBmA~COTGDI?MWk@cDMcCYyA_CiH]w@Wc@oA}@q@k@uA{AyAqA}BmBiB_@cF}AgEuBaEwBw@]qBcAICIAIDGJS|@MZIDa@FKFGHOZgD~Ke@vAkA|DgCpIGHGBICqA{@]g@i@_AeEmGqAuBo@{@yAaCaFsHu@wAcAoAyBmDcF{HaBoCq@uAoBkFk@cB}@yDa@aCo@gF[cEa@cE?Y}@kJgBySg@yEGiB?u@FW\\k@?MC?PDTLFL^\\\\Rv@v@FDNGj@b@n@l@bHbGzAtArD`DbDlCrBfBnEnDfBnAf@`@dDvBdFpD~BxArCxBx@h@fEzClHbFDF@N}CvNIh@A\\BNPP`FjCjC~A~@p@FH?ZOt@_@zBM|@[~A[nBOtA?ZFHRLt@ZvC~At@ZfBb@`Cp@r@PXJlBfBtD|Cl@d@z@v@h@z@`@dArAbE`@vAJb@Jv@XxCb@zBJVHDH?RMP[v@}BjA{BlEwFn@kATg@FKHEH?HFd@hB",
    },
    {
      stravaId: 8741378792,
      name: "Rower #4 2023",
      distance: 14653.4,
      movingTime: 2256,
      elapsedTime: 2272,
      totalElevationGain: 69.2,
      sportType: "Ride",
      startDate: "2023-03-19T13:08:41",
      startDateLocal: "2023-03-19T14:08:41",
      startLatlng: [50.21693420410156, 22.109176635742188],
      endLatlng: [50.21690368652344, 22.108985900878906],
      private: false,
      averageSpeed: 6.495,
      maxSpeed: 9.5,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "y~nqHie}eCCMGIUE}@A_A_@uDeCMAMFO^U|@GDIAkCcB}A}@gMoI_B_AyByAuBoAG@ENE^BzBVjELdDVtDPbBIb@q@vBO\\KDKAWSy@u@aAyAcAuBeDwKGIICKBKJqAfCkAxAiCjDu@|A}@`CILY^EJCN?p@WhEGnA?|@NzMl@`TTnNKlIJlOCxGWbOUxTK|CI`CGn@m@rFCJEHI@IAeDcBu@g@}GwDaBeAu@q@{CcD{EiGYa@_@c@WIEIEO?O?iHIa@QYCO}@{Hm@iHIa@[{Au@qCa@iAoCeG_@m@WYUWg@_@u@a@[Ky@IyAI]?uAGYG}As@YGW@WL[d@_@~@O^IJKFK@MEYOoAw@uAgAwAoBm@cAe@q@oAuAqB{A{Ay@c@_@cBeAOKAI?O|Ao@lAw@jAy@\\_@P[fBqFpB_Gv@mCtAqDzAwEzCmKr@oCNc@LY@Mb@mAH]@a@GMMOc@Oa@[a@e@o@aAeNeTuB{CgB{C_B}BkAkBmE}GaBmC{AwCmBuFs@cCs@mD_@cCe@kEwBeV_@{EsBqTEwA?s@BORc@NOFEF?~BhBNNJDNEtEhErC`C~AvA`At@hDrCxBtBl@d@zBnBvB`B~G`FrHdFhCjBrFvDv@n@vHbFdAx@@LALi@xBkB~IQx@C\\BLDJHHt@\\dE|BvDbCBD?VeAtGq@lEIv@ATBFDHTP`F~BvAf@xD`A~@Z\\VrFxERHZ?HD^p@n@t@^r@xBrGj@vBRhBF|@p@nDJRN?X[`AmCpAgCvCmDbAwAv@{ANMF@FFjBxGbApCl@rAlAhBXXt@h@HBH?FCNWp@}BFo@Cc@WoCMkBc@}JAgABs@@KHEb@JHPRPpDbC~@p@jHrEvIxFRD^Bb@THEDKRcADOJEL?VLr@l@hBjAnAh@fAVLV@N",
      summaryPolyline:
        "{wpqHoq}eCk@mBGIICKBKJqAfCkAxAiCjDu@|A}@`CILY^IZ?p@]dGApANzMl@`TTnNKlIJlOCxGWbOUxTK|CO`De@tEMx@EHI@IAoCuAkAu@}GwDaBeAu@q@{CcD{EiGYa@_@c@WIEIEO?O?iHIa@QYCO}@{Hm@iHIa@[{Au@qCa@iAoCeG_@m@WYUWg@_@u@a@[Ky@IyAI]?uAGYG}As@YGW@WL[d@_@~@O^IJKFK@MEYOoAw@uAgAwAoBm@cAe@q@oAuAqB{A{Ay@c@_@cBeAOKCM@K|Ao@lAw@jAy@\\_@P[fBqFpB_Gv@mCtAqDzAwEzCmKr@oCNc@LY@Mb@mAH]@a@GMMOc@Oa@[a@e@o@aAeNeTuB{CgB{C_B}BkAkBmE}GaBmC{AwCmBuFs@cCs@mD_@cCe@kEwBeV_@{EsBqTG{B@OJ]Ze@FEF?FB`@^hBvAFBNEFDLNxClCd@d@rC`C~AvA`At@hDrCxBtBl@d@zBnBvB`B~G`FrHdFhCjBrFvDv@n@vHbFdAx@@LALi@xBkB~IQx@C\\BLDJHHt@\\dE|BvDbCBD?VeAtGq@lEIv@ATBFDHTP`F~BvAf@xD`A~@Z\\VrFxERHZ?HD^p@n@t@^r@xBrGj@vBRhBF|@p@nDJRN?X[`AmCpAgCvCmDbAwAv@{ANMF@FFf@dB",
    },
    {
      stravaId: 8707570315,
      name: "Rower #3 2023",
      distance: 11930.8,
      movingTime: 1943,
      elapsedTime: 1960,
      totalElevationGain: 59,
      sportType: "Ride",
      startDate: "2023-03-13T13:45:44",
      startDateLocal: "2023-03-13T14:45:44",
      startLatlng: [50.216957092285156, 22.109773635864258],
      endLatlng: [50.21693801879883, 22.10906219482422],
      private: false,
      averageSpeed: 6.14,
      maxSpeed: 12.7,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "}~nqHai}eCRpCCEDC@YENAEG?GKMEqAW}@[u@o@sBqAMCMDKJ_@tAGFKAsCsBuJmGwEuC{E}Cm@_@UIIBGLANBlCt@pNV~CCPWn@o@pBMFK?IE}@cA}@oAq@oAa@eAwCsJIMIIKAIDKJiAzBiBvBiBfCw@zA_AbCQ\\IHKDKCGKKu@c@kBMeCUuAaCwHYs@[i@}@k@qBqBkD{CmA_A[M{Cs@gCu@iHkDuEaCmAk@KCMDGJ[nAKLk@JMJINiHzU}@|CiBxFQt@GFK@ICM][uAYq@mGuJyEgHgEuGwAoBkAwBoJaOqA_CiBqDi@oAESI_Ay@cDe@_Ca@eCo@_GK]IIIEa@@_AKaAg@k@a@KQAKBIDCDBh@VLPZZ\\PTBf@@b@EPIFIBMA_@IqAy@qJOuAkAsNkAsMKyCB_@DIh@MJ@r@b@j@f@VFZTRHb@b@rBjBbEnDrIhHTTl@f@HLdAx@|BpBrDzCrDjCnDfCfHxE|KbIdDxBNFt@l@LFRRbAn@BF?JY|AY~@_@`BaAtEWpAALBNDJFFdAj@\\XpDlBfC~Ab@^?JYbA_@|Bm@xDc@dD?RDJPLzDpBjBv@ZDjBh@`B^d@P~@p@`FhEJDJ@NKFOBeAx@eF|A{IbAsGDED?fCxBf@\\JNYlBI`B@LBHFFRB\\CVDr@?j@BVXHNlAxFnAvElAjFBLJTRl@Lj@j@rBzArEZt@`AfBh@p@l@l@b@ZNDDANSt@gCBMB]GwASoBIqAe@oJ@kC?MJMTJJLf@\\nItFvGhEdEdCvAbAFDr@FLKDKXaAFGJCHBj@h@rAv@NNxB`Av@PHAHPDV@CGCCI",
      summaryPolyline:
        "axpqHcr}eCUy@O]IIKAIDKJiAzBiBvBuAjB]j@u@xAw@tBQ\\IHKDKCGKKu@c@kBMeCUuAaCwHYs@[i@}@k@qBqBkD{CmA_A[M{Cs@gCu@iHkDuEaCmAk@KCMDGJ[nAKLk@JMJINiHzU}@|CiBxFQt@GFK@ICM][uAYq@mGuJyEgHgEuGwAoBkAwBoJaOqA_CiBqDi@oAESI_Ay@cDe@_Ca@eCo@_GK]IIIEa@@_AKaAg@k@a@KQAKBIDCDBh@VLPZZ\\PTBf@@b@EPIFIBMA_@IqAy@qJOuAkAsNkAsMKyCB_@DIh@MJ@r@b@j@f@VFZTRHb@b@rBjBbEnDrIhHTTl@f@HLdAx@|BpBrDzCrDjCnDfCfHxE|KbIdDxBNFt@l@LFRRbAn@BF?JY|AY~@_@`BaAtEWpAALBNDJFFdAj@\\XpDlBfC~Ab@^?JSt@Ov@cAlGc@dD?RDJ`Al@`A`@hAn@jBv@ZDjBh@`B^d@P~@p@`FhEJDJ@NKFOBeAx@eF|A{IbAsGDED?fCxBf@\\JNYlBI`B@LBHFFRB\\CVDr@?j@BVXHNHTD`@b@lBp@xCv@pClAjFBLJTRl@VfA",
    },
    {
      stravaId: 8580815239,
      name: "Rower #2 2023",
      distance: 7390.6,
      movingTime: 1343,
      elapsedTime: 1424,
      totalElevationGain: 17.4,
      sportType: "Ride",
      startDate: "2023-02-18T11:53:13",
      startDateLocal: "2023-02-18T12:53:13",
      startLatlng: [50.216880798339844, 22.109081268310547],
      endLatlng: [50.2169189453125, 22.109086990356445],
      private: false,
      averageSpeed: 5.503,
      maxSpeed: 7.922,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "o~nqHwd}eCCF?WOOc@Mm@C_@Wc@ScDqBWMK?KDGL]rAEBE?yMwIeIeFuBuAm@_@}@]IAGFGZFfCn@lMZlDE\\I^u@`CGFK@KE_@Y{@_Ao@_AYi@o@yAs@oBcBgGK[GGIAIDIJkAzBoErFgAtBKJG?YuAy@gCUe@KCIBIFOl@EBG?EGQu@g@eBqAaEWk@[g@c@W}@u@eGyFgAy@UIsAWyDeA}FuCSMGMCO@OJc@fBkLb@_Cp@yEhAyICOEGyA{@mGkEGIEi@K]@KBDD?BDDCOTAGIIDCRLCIBGMhAEJK@YYIDCHYdBkBxI]hBCT@LNP`FjC~@j@nBpAj@TDH?PCTOb@I`@_@|Ba@`Cq@jE@PPZNBPHb@TLJn@TzBfAfA\\fATtBl@TDh@RpGpF~@n@`A~@l@dAbAxCzA~EJHH?HMHa@DIFGHAFDNn@hApDN\\FHJ?HIVo@j@kA|@qArAyAbAuAdAmBDGFAHBDHt@lCjAzDj@~Aj@jAR^l@z@`AbA\\RN?HCLSd@uAV_AB]q@wI[sGC}C@OHKpD`C|B`BhTbNRFd@APa@Ty@JIJAr@j@rCbBn@ZzAb@JTA@?J@GCI",
      summaryPolyline:
        "}wpqHuq}eCi@mBGGIAIDIJkAzBoErFgAtBKJG?YuAy@gCUe@KCIBIFOl@EBG?EGQu@g@eBqAaEWk@[g@c@W}@u@eGyFgAy@UIsAWyDeA}FuCSMK]@OJc@fBkLb@_Cp@yEhAyICOEGyA{@mGkEGIEi@K]@KBDD?BDDCOTAGIIDCRLCIBGMhAEJK@YYIDCHYdBkBxI]hBCT@LNP`FjC~@j@nBpAj@TDH?PCTOb@I`@_@|Ba@`Cq@jE@PFNHJNBPHb@TLJn@TzBfAfA\\fATtBl@TDh@RpGpF~@n@`A~@l@dAbAxCzA~EJHH?HMHa@DIFGHAFDNn@hApDN\\FHJ?HIVo@j@kA|@qArAyAbAuAb@y@f@{@FAHBDHd@fB",
    },
    {
      stravaId: 8325716462,
      name: "Rower #1 2023",
      distance: 10801.9,
      movingTime: 1753,
      elapsedTime: 1768,
      totalElevationGain: 48,
      sportType: "Ride",
      startDate: "2023-01-02T13:48:28",
      startDateLocal: "2023-01-02T14:48:28",
      startLatlng: [50.21687698364258, 22.10919952392578],
      endLatlng: [50.21689224243164, 22.108938217163086],
      private: false,
      averageSpeed: 6.162,
      maxSpeed: 9.752,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "m~nqHme}eCKSIEYAKCYCUGSMc@MeBkAk@[k@a@M?KFIJ[pAEFG?cRwLcAs@{CmBcEaCG@GRAtBVxELvCh@|Hg@nB]|@IFKDKCIEa@_@a@c@u@eAk@uAwAsDe@aBy@gDMWICK@IFwAhCkEvF]l@m@nAaAbCa@h@CNE~AUrDC|@AhBBhDPvJf@lPTxM@`AIrDCzC@|AJlG?lCE`G@z@c@|RItNKfEGnAOlBg@hECJMJSAUM_B{@gKeG{AaA][wC_D_GqHe@k@a@WEUAa@BaAG{ECQQ]ES{AcO_@wCq@cDs@{BcA{BuAmC_@k@_@e@s@k@i@Y]M]Iy@I}CG[Ci@OsAq@]EM@MFWVS^s@bBIFM@KCwBoAmA_ASWgBsCeAwA]_@s@o@oA_As@_@mA{@_Ag@y@u@?QXS`AY`@Q`CaBTUN]x@mCtA{DdC{Hx@{BxAoErAiEtCiKpA{D\\yAZiAdAgDfAuDFKl@_Cd@sAjC}ILWNQHEP@RGJWZmAFGFC`GzC~BfA`DdB`Bn@~FxAZNr@h@xDjD~BhBj@n@\\n@`@dArBvGDVA?DPLJJ@DGNcAFGFAHJXfAjAjDJNF@DCtAgC`CyCd@q@^a@jA}BFGH@FDDH|@dDlArDt@nBv@vAbApA|@p@P@FCPa@Lc@f@yAB_@_@uEg@{JEeA@aCBMD?TJBDbEjC~AhA~@h@zEzChAx@~IzFFEVm@Fa@J]FIJCJ@d@`@dBhAnAr@^LjAZP\\D@FJADE?",
      summaryPolyline:
        "{wpqHer}eCa@eBGIICK@STmAzBiDlEk@x@iA|By@rBGJQPKZE~AWfECrCBhDPvJf@lPTxM@`AIrDCzC@|AJlG?lCE`G@z@c@|RItNQfGQ|Bg@hEIRGBG?a@O_B{@gKeG{AaA][wC_D_GqHe@k@a@WEUAa@BaAG{ECQQ]ES{AcO_@wCq@cDs@{BcA{BuAmC_@k@_@e@s@k@i@Y]M]Iy@I}CG[Ci@OsAq@]EM@MFWVS^s@bBIFM@KCwBoAmA_ASWqB_D{@kA]_@gAaA{@m@s@_@mA{@_Ag@w@s@CI@IXSlA_@j@Yf@a@bAq@TUN]x@mCtA{DdC{Hx@{BxAoErAiEtCiKpA{D\\yAZiAdAgDfAuDFKl@_Cd@sAjC}ILWNQHEP@RGJWVaAJSFCF@xFxCtB`AjDjB`Bn@~FxAZNr@h@xDjD~BhBj@n@\\n@`@dArBvGDVA?DPLJJ@DGNcAFGFAHJXfAjAjDJNF@DCtAgC`CyCd@q@^a@dAsBLQH@FDDHf@lB",
    },
    {
      stravaId: 8043284349,
      name: "Rower #4 2022",
      distance: 23912.7,
      movingTime: 3676,
      elapsedTime: 3762,
      totalElevationGain: 130.4,
      sportType: "Ride",
      startDate: "2022-10-30T14:02:04",
      startDateLocal: "2022-10-30T15:02:04",
      startLatlng: [50.21690368652344, 22.109045028686523],
      endLatlng: [50.21692657470703, 22.109106063842773],
      private: false,
      averageSpeed: 6.505,
      maxSpeed: 10.652,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "s~nqHod}eCQQw@W]UMA[QCGBL`@PXFPHn@JHLFT?G?PI[MMSKSCm@UiDoBk@e@a@QK@KFGNOr@IXIDKCUUiHuEyA{@mBsA_GwDcDoBqAs@GBGTArABpAn@fLb@jFCNW^m@`BILKBKEc@]o@o@_AuAw@}AuAgEg@oBk@kBMSGEIBIFoAfC}@jAURMVgB|BiAzBGBICGK[mAw@gCM[IGEAEDORQf@KGcAmDgAgDg@gAYc@IISEUMg@e@y@aAaG_FOQSIs@Ee@OuCw@g@QqCoAaIaE_CiAMCKBIHWbAGPIJKBW@KDS\\}CzJ{C`KcArDoArDMj@ELIHIBICMU_@yAUi@y@oAuBcD_@e@qAuB{@wAoEaHsCgE{@cAy@aBaGkJ]_@_C_EaAgBo@sAq@mAu@gBEu@i@uBs@cDo@{DW{BQsBMYIGIE_@@i@C{@]_Ak@MMEKBSCQSY]WeEgCmJgGq@Ys@IYDq@X_@b@[n@Mb@g@dCc@xAy@jCuChIg@|As@jCQb@WX[N[DsAB[DWNy@n@kAl@gBdAmD`BqCvAi@HeAHi@LMFUT[j@kApDWp@]l@}@vAy@bAe@`@YPMD]Fm@AiAOmCm@w@Gw@?k@F[Hy@\\u@`@{Ar@i@Di@CWEYIWSUEa@WYIe@IM@KFGJSn@u@rFYrAYt@QTIFUJu@Dk@AiBMUBIFMXG^u@nH{@tGUzBMz@GNKHKBKCa@Sy@]e@GK?KBIJIb@UtBGtAS|BERILKFWDqBKK@o@PsA~@eCxBu@t@g@r@o@rAs@dBmAhCm@x@eBbBk@t@GNKZSlAy@hGiAtGy@~FIb@GJKDKAIIcBgC_@w@gBqE_A_B{@iAeAmAmCoC]YKCWBmBh@a@RmAv@e@Pc@JsAHo@Cy@@UB_@NULcA~@eAdAw@z@[p@a@xAKXGFGBI?YIoDaBcGiCUGKAaA]y@SiGoBm@WuBi@sC_@I?wBUKECGAIFg@HcCBwBFcB?qAQ_BmA_EQmAWiK?{CBsBCsAKsA]eCI}AAuA@uAXiEDeA?oAAw@SsBaAgFk@mEMeBG_CG}J@wABi@^iCJgCDyBFqANgBTcB`A{Fd@aCr@gCfA_DpAuCl@gAl@eAfDkFjAaB`A}@^e@^m@FGpBOdEg@dE]p@K|Ae@|CiA|B_AfBm@hBw@`AY`Aa@x@c@rBs@|CkAfFuBxE_BbBu@v@Uj@WdDqAtBu@r@Y\\MRCf@UxBw@hBs@d@Wr@YXGLIrAg@x@Sj@IfBE|@B\\D|BD\\CxBFvA?v@FNDdACv@BrAAfDHnB?d@BbB@zBJ\\?LApD@rENbAPxBj@z@P`AV`Cv@?EEEdBl@fDv@fIxBdCh@dBh@bAVTBv@@TBrFtAF?NKH?\\Nr@Lh@F~AF~@ERGPMt@_AFCb@BNHFFP`@DP@d@DLLAVMTA~@Fj@Fj@N^NbAh@n@d@x@x@b@h@`@l@z@`BLd@?RGf@FbAJXNRJF\\Bp@MJDpB`BVVPJR?FBtY|VtD~CbDfCvDlC|IbG`EzCxBvAxB|A|GvEz@n@BJEVUx@k@hCmAdGWfAA\\BJHH`Bx@`DhBrChBf@`@@FANQl@yAtJY|B@RFHh@XlExBnAb@n@JfElAtDvCfCxBj@`@r@t@d@t@Vn@nBfG`@hAHFH?FILo@HEJBFHFZ~A~EDBHADGpAaCtDqE^o@b@{@TWLUFEHBDJx@`Db@vAnApDd@~@Xf@dAtAbAz@H@J?HELYl@sBH]B_@Gs@GgAg@yHCaAOeC@oCDOfDvBh@`@HJb@RrA~@lEpCXLh@b@pCbBdAv@bCxAz@^H@HCLUPu@JYHGJ@nA~@bAn@bAd@NJLHN@jA\\JL",
      summaryPolyline:
        "_xpqHyq}eCe@_BMSQAQToAdCkArAMVgB|BiAzBGBICGK[mAw@gCM[IGKBORQf@KGkCuIg@gAYc@]OUMg@e@y@aAqGqFSIs@EcFyAqCoAaIaEmCmAKBIHWbAGPIJc@DKDS\\}CzJ_FtPoArDMj@OVS?MU_@yAUi@oDsF_@e@mCmEoEaHsCgE{@cAy@aBaGkJ]_@_C_EcDiGu@gBEu@i@uBs@cDo@{DW{BQsBMYSMiAA{@]mAy@EKBSCQSY]WeEgCyJoGq@Uu@C}@\\_@b@[n@Mb@g@dCc@xAy@jCuChIg@|As@jCQb@WXw@ToBHqA~@sDrB_IxDoBRw@TUT[j@kApDWp@]l@}@vAy@bAe@`@YPk@Lm@AiAOmCm@w@Gw@?gAPkErBi@DaAIYIWSUE{@a@s@GKFGJSn@u@rFYrAYt@QT_@Ru@DuCO_@JMXG^u@nH{@tGUzBMz@GNKHKBgBu@e@GWBIJIb@UtBGtAS|BO`@KFWD}BIo@PsA~@eCxBu@t@g@r@o@rAs@dBmAhCm@x@eBbBk@t@MZY|Ay@hGiAtG_ArGCNGJKDKAIIsBaDkAsCc@mAa@w@e@u@aCwCmCoC]YKCeCl@oBjAiA\\sAHiBAu@RULcA~@}B`C[p@a@xAKXGFQBmMuF}C{@wHgCuBi@uGu@KEEQFg@HcCBwBFcB?qAQ_BmA_EQmAWiK?{CBsBCsAKsA]eCKmB@{CZaFDaBAw@Ey@OuAaAgFo@eFImAG_CG_MD_AZuBDg@PaGTeDTcBtAgIv@{Cn@qBd@oApAuCzAmCtEkHd@k@x@s@^e@^m@FG|NuAp@K|Ae@lNoF`AYzBeApG_CfFuBxE_BbBu@v@UpEiB|JoDhBs@xAq@XG`Bq@x@Sj@IfBExENnFBfALpEAvGHdGP|E?rENxFnAbEnAEKdBl@nNpDdCh@rDbAxAFrFtAVKH?RJfAR~BLhAGd@[j@w@FCX@XJNPL^Bn@DLn@OjBJ`ATbB|@v@l@t@x@v@fAz@`BLd@?RGf@FbAJXNRh@Jp@MJDhCxBPJZBtY|VxIfHvDlC|IbG`EzCxBvArMdJBJEVUx@k@hCeBlIA\\BJHH`Bx@`DhBzDjC@FANQl@uAbJ[dCATHPvFrCnAb@n@JfElAtDvCrDzCr@t@d@t@Vn@pCpIHFH?FILo@HEJBFHFZxAvEJJNIzAkCrDsEr@sAV_@DCLUFEHBDJb@dB",
    },
    {
      stravaId: 8022920830,
      name: "Rower #3 2022",
      distance: 23894.6,
      movingTime: 3893,
      elapsedTime: 3983,
      totalElevationGain: 130.1,
      sportType: "Ride",
      startDate: "2022-10-26T14:26:07",
      startDateLocal: "2022-10-26T16:26:07",
      startLatlng: [50.21706771850586, 22.109329223632812],
      endLatlng: [50.21690368652344, 22.10896873474121],
      private: false,
      averageSpeed: 6.138,
      maxSpeed: 9.564,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "s_oqHif}eCIDQRBIGG}@U[MUQSIOK_@[_@Ss@k@[MG?IBGH]hAONMKUMqJkGsGcEqBkAgEqCg@UE?ELATB`Cd@xIFxBNvALrBE`@Sd@]pAMTGDK@ICs@m@_@a@]c@aAaBq@_BYgAuB{GMYIEI@IHiA`CiBxBgBbCaAjB_AdC[^GBIAGGOaAa@eBQqCUoAk@qB}AsEk@eA{@cASGSOeAeAmCyBu@q@aAu@WMe@GmEgA}@]uAq@c@W_CgAmCwAwDkBK?IFIJMr@K`@KHKBW?KFSVqDtLeF~Py@bCOj@EJKBICGM_@_BYk@gSc[eA{Ac@c@UYi@oAwJmOmAqBuAsCm@gAy@qBCq@k@{Bs@eDa@eC]aCOeBIY?YI[KImAEYGgBaAKIEI?]K]GK]OSQIEwA}@UUWKSOcDwBwEwCw@][GW?a@Jm@^_@b@QZ[bAe@~B[dAeBtFwBfGoAhEYn@YP[Fi@Fu@?WBc@VcAr@kCxAeI`Ei@NqAJYFe@RUVYj@Wn@u@hCk@hAoAlBs@x@m@f@YL[F[BcAMcDq@eAMg@?i@DaAXQ?MOOIUh@IL}@p@o@Vi@@c@Aq@OeCgAKAIBIFMVOx@g@jDIz@SbAOh@a@n@QL]HsAAuBKQHMTKh@En@]dD_AxHYvCKv@Qn@IFIB}As@c@KWCK@IFIJCPo@zIK\\IHIDcBO}@H]H]Pe@\\kDzCs@z@_@j@_AjBWt@e@z@q@xAg@r@iBlBOTKZOTKV_@dBSnAYhCyAbJi@~DIb@MXI@KEIIWe@uAoBO[sBqFuAwBgCwCqAqAe@c@]SUBwA`@sAj@]T]N]Ni@Ng@FuC?UB]Ju@h@yCbD[j@k@tBMPIBOAk@UICE@OMyB_AiCmA{Ao@WGQI}Ac@eA_@QCwCcAMAw@]}@YeA[aAQiAK}@OmBQQKCEAMJ}@PgG@yAAgAQoA{@uCKe@Ku@MmCQ_H@_GCcBBYGQ]sCM{BCqABoA\\}F?}BEk@UmBq@eDo@mESeCI}CIeJ?uAH}@\\kCF}@JkEFqARwBJ{@fAgG^kBPu@lA}Df@sAt@aBVm@dBuChE{GZ_@x@s@^a@PWN]LKzD_@b@Ax@Mz@Gn@MrBOv@MlA]|B}@lBq@^S~@_@nBs@vB}@t@UjBw@h@OvAm@xNoFpCiAr@S^Sb@W~HqCt@[f@YjAe@VGx@c@hA]xAo@d@OVA`Bo@j@KjAMb@BL?f@HxBDj@?|AHhBBdBATB`AElBH~A?dBFj@@`@Cd@FtA@f@C`@@JDb@CVBHAR@NDRETDRCXHVBZCP@XALFd@IJB\\CRBVAf@Ln@Ah@DhAThBj@\\Fd@Rb@HhBb@^PPD?AFBC@EADANAz@XdEfAzAd@nDv@z@XtBf@|A\\nBl@xG`BF@FIDYDErA^~@JzAFx@G`@Uh@w@JINA^FRNRh@@p@DFRIZAfABrATbA\\bAp@fA~@n@x@n@bAp@rADn@En@Br@HXVZPFT@JARKJ?JB\\TnA`Ad@JFD`A`AfJbInGlFpIpHdClBvCtB`HrEb@^bC`BdFpDfEvCn@h@pD|BbBtANFDJCLEHGd@K^eClLIb@AP@RRRbErBlFfDHJuAnIy@nFBTHHnGtClCr@fCl@^Lz@n@b@d@nC|B`A|@pAbAd@l@Xh@pCpIX|AH|@D`A\\rAPdAHVHDBBJ?HCFIRa@p@qBjA}BNWlDeEV_@fAuBDGFAPFt@vCbAbDt@rB~@lB`ArAz@t@PJH?FCHGx@iCBOD_@Aa@]iDc@sHK{D@aB@GHGtFpDtBzAbAl@vCrB|CfBlBtAr@^xA`A\\HR?FEFWRaAFKJGL@r@l@dBdA|@b@ZRx@TTBHFDJD\\",
      summaryPolyline:
        "_xpqHyq}eCq@mBSCQTaAtBqE|FaAjB_AdC[^Q@GGOaAa@eBQqCUoAiCeIk@eA{@cAg@WeAeAeGaFWMe@GeFqA{BeAc@WoL_Ga@KSRMr@K`@KHc@B_@^qDtLeF~Py@bCOj@EJKBICGM_@_BYk@gSc[eA{Ay@}@i@oAeM_SuAsCm@gAy@qBCq@k@{Bs@eDa@eC]aCOeBIY?YI[KIgBMgBaAQS?]K]GK]OcDwBwDgCwEwCw@]s@Ga@Jm@^_@b@QZ[bAe@~B[dAeBtFwBfGoAhEYn@YP[FwBJgBjAkCxAeI`Ei@NkBRe@RUVYj@mAxDk@hAoAlBs@x@m@f@YLw@JcAMcDq@eAMqADaAXQ?]Y_@v@}@p@o@Vi@@c@Aq@OeCgAU@IFMVOx@q@fFSbAOh@a@n@QL]HiEMQHMTKh@c@tE_AxHYvCKv@Qn@SJ}As@c@KWCUHIJCPo@zIK\\SNcBO{AR]Pe@\\kDzCs@z@_@j@_AjBWt@wAtCg@r@iBlBOTKZOTKV_@dBm@xEyAbJi@~DOp@GJI@UOuBcD{B_GuAwBgCwCqAqAe@c@]SmBd@sAj@{@d@gA^g@FuC?s@Nu@h@yCbD[j@k@tBMPQBcAYOM_J}DwJ}CMAuBw@yBi@cGq@QKESJ}@RsHAuBQoA{@uCW{AMmCQ_H@_GCcBBYGQ]sCM{BCqABoA\\}F?}B[yCk@mCW}A]gCOoBMsDIgLD}@\\kCH{@PkGV_DJ{@lBeK^wA`B}EdAaCl@eAhGyJZ_@xAuA`@u@LK~Ea@dDc@rBOdCk@jFoBhNsFh@OvW{JbAk@~HqC|Au@bBm@x@c@hA]xAo@|@Q`Bo@j@KjAMxALdDD|AHdFD`AErHPlAAd@F|BApABdAHREzANfACLFd@ItA@f@Lx@AhBZlDfAlCl@x@XI?TC|IfCnDv@xSnFF@FIDYDErA^~@JzAFx@G`@Uh@w@ZK^FRNRh@@p@DFn@KfABrATbA\\\\TlBzAdAvAdApBDFD^E~@Br@HXVZf@H^MVBlBvAl@P`A`AfJbI`R~OdClB`RjMlLhIn@h@pD|BrB|ADJQ|@qClMKt@@RRRbErBlFfDHJoC~PBTHHnGtCtHnBz@n@b@d@bH~Fd@l@Xh@pCpIX|AN~Bx@pDLHJ?PMRa@p@qBjA}B|D}EV_@lA}BXDd@lB",
    },
    {
      stravaId: 7926073669,
      name: "Rower #2 2022",
      distance: 10848,
      movingTime: 1639,
      elapsedTime: 1712,
      totalElevationGain: 47.9,
      sportType: "Ride",
      startDate: "2022-10-07T14:20:32",
      startDateLocal: "2022-10-07T16:20:32",
      startLatlng: [50.217071533203125, 22.109193801879883],
      endLatlng: [50.216922760009766, 22.108993530273438],
      private: false,
      averageSpeed: 6.619,
      maxSpeed: 9.27,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "u_oqHme}eCL`@I_@_@Q_AWk@WkBsAeAq@KCKBIHELWbAIJIAoNaJcFgDoAs@aDuBy@]I@IFCLDvAAx@f@dKd@pFCb@{@nCILIFKAqAaAm@y@[g@_AwBo@kB{@sCo@eCMSICI@IFqAdCw@~@oCnDaAhBiApCU\\MFE?CbBYbFCxBLvJLrFf@nPNhMKhIJnL?tFGpGU`LMdNUvJQjCe@vECNGJIBK?mCyAwLaHYUe@c@aEqE{EmGa@c@OCIGEWBiAEuFCQQYEOOiAk@cGg@iEKiAUyAw@iDk@aB}BaFm@eA_@e@m@i@WQa@Uk@S{@Mq@?wCMWIuAk@e@IW@KDURYj@e@pAGJKDK?KEqBgAeAw@SW}AgCuAqBs@u@g@c@y@m@qAq@y@k@o@[eAs@QU@ORSr@M`@OVMdCgBZg@dAcD~AoEbCwH`AeC~AiFrE{Or@wBv@{ChA{DbIyWPc@LSHC\\APMJWNw@BKFGHAHBnBfA|Ar@`KfF`@L|Bh@t@TdATl@V`Al@vA~AtBdBxAhAh@p@b@z@f@tAdBrFTfAP|BPbAb@vBFLFHJBHCHKnAcDbAkBdB_CnB}B`AsBFGFEH@FDFJxAhFzAhEbAhBr@dAdAv@HDH@HCNYTy@Vs@H[D]Aa@Ga@YkDKwBS}CIoC?wA?q@HKB?LDZXdBdApHdFjGxDvFtDj@ZTDHCNYReAFMJEJ@b@ZhDvBr@ZdAXJJBL?L",
      summaryPolyline:
        "}wpqHsq}eCi@oBGGICI@IFqAdCyBnCaBzBw@|A_A`CU\\MFE?AFAzAYbFCxBLvJLrFf@nPNhMKhIJnLAjGEzFU`LMdNWjKOvBe@vECNGJIBK?yCaBkLyGYUe@c@aEqE{EmGa@c@OCIGEWBiAEuFCQQYEOOiAk@cGg@iEKiAUyAw@iDk@aB}BaFm@eA_@e@m@i@WQa@Uk@S{@Mq@?wCMWIuAk@e@IW@KDURYj@e@pAGJKDK?KEqBgAeAw@SW}AgCuAqBs@u@g@c@y@m@qAq@y@k@o@[eAs@MMEIBMRSr@M`@OVMdCgBZg@dAcD~AoEbCwH`AeC~AiFrE{Or@wBv@{ChA{DbIyWPc@LSHC\\APMJWNw@BKFGHAHBnBfA|Ar@`KfF`@L|Bh@t@TdATl@V`Al@vA~AtBdBxAhAh@p@b@z@f@tAdBrFTfAP|BPbAb@vBFLFHJBHCHKnAcDbAkBdB_CnB}B`AsBFGFEH@FDFJb@|A",
    },
    {
      stravaId: 7731841366,
      name: "Rower #1 2022",
      distance: 10735.7,
      movingTime: 1518,
      elapsedTime: 1518,
      totalElevationGain: 47.7,
      sportType: "Ride",
      startDate: "2022-08-31T15:48:12",
      startDateLocal: "2022-08-31T17:48:12",
      startLatlng: [50.217079162597656, 22.109233856201172],
      endLatlng: [50.21738052368164, 22.109264373779297],
      private: false,
      averageSpeed: 7.072,
      maxSpeed: 9.794,
      averageCadence: 0,
      averageWatts: 0,
      maxWatts: 0,
      deviceWatts: false,
      kilojoules: 0,
      calories: 0,
      deviceName: "Strava Android App",
      hasHeartrate: false,
      averageHeartrate: 0,
      maxHeartrate: 0,
      polyline:
        "w_oqHue}eCSKWGkAc@]SmBmAw@c@KAIDILYjACDEBGAyBwAuFkDcG_EuD{BkD}Bk@UIBGJCN@vBj@bLb@pFE`@cAzCKHMAKGo@q@{@cAu@sAo@yA{@iCcB}FGGIAIDIJmA|BgBvBgBzBcAnB{@`COXYZCNGrBSfDGlBP~Ml@xTVdM?v@MfIJ|J@lDGlJY|ME|EM`LKrDYxD]dDIVIDIAaB_AiAk@wFeDeB_AoBsAwC{C{@cAmFeHMISIIMCS@kAEuB?qACg@EQQ]CQi@sFUcBKqA[aDW_Bq@{Cg@}AgBaEo@sA_@o@c@g@}@w@qAi@w@Mg@?aDO}@Y{@_@YGYBKF_@b@Q\\]`AQXKBYI{A{@yAgAqDoFs@{@gA{@YMYYc@U}@s@aDsBAQBGzAg@b@Ul@e@jAw@TYHO`AwCzAkEbCoHhA}C~@wCzEsP~@yCZy@p@uC|CkK|@eDp@kBpByGNa@LSNKN?TSHMXaAFKJCJ@zEbCr@b@lHpDbA\\|EjAt@Vz@r@zCnCtC|B`@f@h@~@`@fAnBhGLd@Jx@PxBn@dDJVFDJ?HEFIfAsCnAaCnEwFl@iAXs@HEJAHHh@vBz@pC`AtCh@hAt@nAjAvAh@^J@JEHKL]f@cBHc@@e@c@gF]eGK{C?yA@i@@CFAHBlBlAjJjGtBpApIpFp@\\b@JJ@HAHKPcAFMJGL?LFRTHFbCxAz@^NLBF",
      summaryPolyline:
        "{wpqHsq}eCk@mBGGIAIDIJmA|BgBvBgBzBcAnB{@`COXYZCNGrBU|DClBNhMl@xTVdM?v@MfIJ|J@lDGlJY|ME|EM`LKrDYxD]dDIVIDIAaB_AiAk@wFeDeB_AoBsAwC{C{@cAmFeHMISIIMCS@kAEuB?qACg@EQQ]CQi@sFUcBKqA[aDW_Bq@{Cg@}AgBaEo@sA_@o@c@g@}@w@qAi@w@Mg@?aDO}@Y{@_@YGYBKF_@b@Q\\]`AQXKBYI{A{@yAgAqDoFs@{@gA{@YMYYc@U}@s@{CoBECAQBGzAg@b@Ul@e@jAw@TYHO`AwCzAkEbCoHhA}C~@wCzEsP~@yCZy@p@uC|CkK|@eDp@kBpByGNa@LSNKN?TSHMXaAFKJCJ@zEbCr@b@lHpDbA\\|EjAt@Vz@r@zCnCtC|B`@f@h@~@`@fAnBhGLd@Jx@PxBn@dDJVFDJ?HEFIfAsCnAaCnEwFl@iAXs@HEJAHHh@vB",
    },
  ];
};
