export interface IActivity {
  stravaId: number;
  name: string;
  distance: number;
  movingTime: number;
  elapsedTime: number;
  totalElevationGain: number;
  sportType: SportType;
  startDate: string;
  startDateLocal: string;
  startLatlng: [number, number];
  endLatlng: [number, number];
  private: boolean;
  averageSpeed: number;
  maxSpeed: number;
  averageCadence: number;
  averageWatts: number;
  maxWatts: number;
  deviceWatts: boolean;
  kilojoules: number;
  calories: number;
  deviceName: string;
  hasHeartrate: boolean;
  averageHeartrate: number;
  maxHeartrate: number;
  polyline: string;
  summaryPolyline: string;
}

export type SportType =
  | "Undefined"
  | "AlpineSki"
  | "BackcountrySki"
  | "Badminton"
  | "Canoeing"
  | "Crossfit"
  | "EBikeRide"
  | "Elliptical"
  | "EMountainBikeRide"
  | "Golf"
  | "GravelRide"
  | "Handcycle"
  | "HighIntensityIntervalTraining"
  | "Hike"
  | "IceSkate"
  | "InlineSkate"
  | "Kayaking"
  | "Kitesurf"
  | "MountainBikeRide"
  | "NordicSki"
  | "Pickleball"
  | "Pilates"
  | "Racquetball"
  | "Ride"
  | "RockClimbing"
  | "RollerSki"
  | "Rowing"
  | "Run"
  | "Sail"
  | "Skateboard"
  | "Snowboard"
  | "Snowshoe"
  | "Soccer"
  | "Squash"
  | "StairStepper"
  | "StandUpPaddling"
  | "Surfing"
  | "Swim"
  | "TableTennis"
  | "Tennis"
  | "TrailRun"
  | "Velomobile"
  | "VirtualRide"
  | "VirtualRow"
  | "VirtualRun"
  | "Walk"
  | "WeightTraining"
  | "Wheelchair"
  | "Windsurf"
  | "Workout"
  | "Yoga";
